<?php
/**
 * MenuApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MenuApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MenuApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for api1ComboCalculatePost
     *
     * Calculate combo price.
     *
     */
    public function testApi1ComboCalculatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api1ComboPost
     *
     * Get combos info.
     *
     */
    public function testApi1ComboPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api1NomenclaturePost
     *
     * Menu..
     *
     */
    public function testApi1NomenclaturePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api1StopListsAddPost
     *
     * Add items to out-of-stock list.  (You should have extra rights to use this method)..
     *
     */
    public function testApi1StopListsAddPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api1StopListsCheckPost
     *
     * Check items in out-of-stock list..
     *
     */
    public function testApi1StopListsCheckPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api1StopListsClearPost
     *
     * Clear out-of-stock list.  (You should have extra rights to use this method)..
     *
     */
    public function testApi1StopListsClearPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api1StopListsPost
     *
     * Out-of-stock items..
     *
     */
    public function testApi1StopListsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api1StopListsRemovePost
     *
     * Remove items from out-of-stock list.  (You should have extra rights to use this method)..
     *
     */
    public function testApi1StopListsRemovePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api2MenuByIdPost
     *
     * Retrieve external menu by ID..
     *
     */
    public function testApi2MenuByIdPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for api2MenuPost
     *
     * External menus with price categories..
     *
     */
    public function testApi2MenuPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
