<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create custom_role_assignment table (custom roles from customization modules)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE custom_role_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, user_id INT NOT NULL, role_key VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_custom_role_assignment ON custom_role_assignment (workspace_id, user_id, role_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE custom_role_assignment');
    }
}
