<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260710130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create stamp-card tables (stamp_program, stamp_progress)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stamp_program (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, is_enabled BOOLEAN NOT NULL, required_count INT NOT NULL, reward_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_stamp_program_workspace ON stamp_program (workspace_id)');

        $this->addSql('CREATE TABLE stamp_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, customer_id INT NOT NULL, current_stamps INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_stamp_progress_customer ON stamp_progress (workspace_id, customer_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE stamp_progress');
        $this->addSql('DROP TABLE stamp_program');
    }
}
