<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260708190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create audit_log table (change history of key business entities)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_id INT DEFAULT NULL, actor_label VARCHAR(255) NOT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id INT DEFAULT NULL, changes JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_created ON audit_log (created_at)');
        $this->addSql('CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_actor ON audit_log (actor_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit_log');
    }
}
