<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260715231000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop legacy workspace_custom_module table after single-tenant customization switch';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS workspace_custom_module');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS workspace_custom_module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, slug VARCHAR(64) NOT NULL, is_enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_workspace_custom_module ON workspace_custom_module (workspace_id, slug)');
    }
}
