<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create workspace_feature_grant table (per-workspace feature grants on top of tarif)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE workspace_feature_grant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, feature VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_workspace_feature_grant ON workspace_feature_grant (workspace_id, feature)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE workspace_feature_grant');
    }
}
