<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260705103800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user, code and authorize_token tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE authorize_token (id VARCHAR(36) NOT NULL, refresh_token TEXT NOT NULL, expires_at INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_574A4E9AA76ED395 ON authorize_token (user_id)');
        $this->addSql('CREATE TABLE code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, code_type VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, brith_date DATE NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE authorize_token ADD CONSTRAINT FK_574A4E9AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE authorize_token DROP CONSTRAINT FK_574A4E9AA76ED395');
        $this->addSql('DROP TABLE authorize_token');
        $this->addSql('DROP TABLE code');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
