<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260709140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create loyalty tables (program, account, redemption, transaction); add points columns to order';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE loyalty_program (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, is_enabled BOOLEAN NOT NULL, earn_rate_basis_points INT NOT NULL, point_value_kopecks INT NOT NULL, redeem_max_percent_basis_points INT NOT NULL, points_lifetime_days INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_loyalty_program_workspace ON loyalty_program (workspace_id)');

        $this->addSql('CREATE TABLE loyalty_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, customer_id INT NOT NULL, points_balance INT NOT NULL, reserved_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_loyalty_account_customer ON loyalty_account (workspace_id, customer_id)');

        $this->addSql('CREATE TABLE loyalty_redemption (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, account_id INT NOT NULL, order_id INT NOT NULL, customer_id INT NOT NULL, points INT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_loyalty_redemption_order ON loyalty_redemption (order_id)');
        $this->addSql('CREATE INDEX idx_loyalty_redemption_account ON loyalty_redemption (account_id)');

        $this->addSql('CREATE TABLE loyalty_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_id INT NOT NULL, workspace_id INT NOT NULL, order_id INT DEFAULT NULL, type VARCHAR(20) NOT NULL, points INT NOT NULL, balance_after INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_loyalty_transaction_account ON loyalty_transaction (account_id)');
        $this->addSql('CREATE INDEX idx_loyalty_transaction_order ON loyalty_transaction (order_id)');

        $this->addSql('ALTER TABLE "order" ADD points_spent INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE "order" ADD points_earned INT DEFAULT 0 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "order" DROP points_earned');
        $this->addSql('ALTER TABLE "order" DROP points_spent');
        $this->addSql('DROP TABLE loyalty_transaction');
        $this->addSql('DROP TABLE loyalty_redemption');
        $this->addSql('DROP TABLE loyalty_account');
        $this->addSql('DROP TABLE loyalty_program');
    }
}
