<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260710120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create loyalty_tier table; add lifetime spend and current tier columns to loyalty_account';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE loyalty_tier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, name VARCHAR(255) NOT NULL, threshold_kopecks INT NOT NULL, earn_rate_bonus_basis_points INT NOT NULL, permanent_discount_basis_points INT NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_loyalty_tier_workspace ON loyalty_tier (workspace_id)');

        $this->addSql('ALTER TABLE loyalty_account ADD lifetime_spent_kopecks INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE loyalty_account ADD current_tier_id INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE loyalty_account DROP current_tier_id');
        $this->addSql('ALTER TABLE loyalty_account DROP lifetime_spent_kopecks');
        $this->addSql('DROP TABLE loyalty_tier');
    }
}
