<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260708130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create workspace and workspace_membership tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE workspace (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(63) NOT NULL, description VARCHAR(1000) NOT NULL, logo JSON DEFAULT NULL, owner_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_workspace_slug ON workspace (slug)');
        $this->addSql('CREATE INDEX idx_workspace_owner ON workspace (owner_id)');

        $this->addSql('CREATE TABLE workspace_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workspace_id INT NOT NULL, user_id INT NOT NULL, role VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_membership_workspace_user ON workspace_membership (workspace_id, user_id)');
        $this->addSql('CREATE INDEX idx_membership_user ON workspace_membership (user_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE workspace_membership');
        $this->addSql('DROP TABLE workspace');
    }
}
