<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260708170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create kitchen_profile table (per-venue wait-time tuning)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE kitchen_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, venue_id INT NOT NULL, base_minutes INT NOT NULL, per_unit_minutes INT NOT NULL, parallel_capacity INT NOT NULL, delivery_minutes INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_kitchen_profile_venue ON kitchen_profile (venue_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE kitchen_profile');
    }
}
