<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260711120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create menu_combo table (sellable combos linked to menu items)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE menu_combo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, venue_id INT NOT NULL, external_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, discount_type VARCHAR(32) NOT NULL, discount_value INT NOT NULL, items JSON NOT NULL, position INT NOT NULL, is_available BOOLEAN NOT NULL, is_archived BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_menu_combo_venue_external ON menu_combo (venue_id, external_id)');
        $this->addSql('CREATE INDEX idx_menu_combo_venue ON menu_combo (venue_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE menu_combo');
    }
}
