<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260715223000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблиц control-plane: cp_server, cp_core_release, cp_deployment, cp_owner_subscription, cp_user';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cp_server (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_slug VARCHAR(64) NOT NULL, domain VARCHAR(190) NOT NULL, owner_id INT NOT NULL, workspace_id INT NOT NULL, server_token VARCHAR(128) NOT NULL, core_ref VARCHAR(128) NOT NULL, contract_version VARCHAR(32) NOT NULL, pinned_ref VARCHAR(128) DEFAULT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cp_server_token ON cp_server (server_token)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cp_server_owner_domain ON cp_server (owner_slug, domain)');

        $this->addSql('CREATE TABLE cp_core_release (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ref VARCHAR(128) NOT NULL, contract_version VARCHAR(32) NOT NULL, is_latest BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cp_release_ref ON cp_core_release (ref)');

        $this->addSql('CREATE TABLE cp_deployment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(32) NOT NULL, release_ref VARCHAR(128) NOT NULL, initiator VARCHAR(128) NOT NULL, target_host VARCHAR(190) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE cp_owner_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, tarif_code VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cp_owner_subscription_owner ON cp_owner_subscription (owner_id)');

        $this->addSql('CREATE TABLE cp_tarif (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, description VARCHAR(1000) NOT NULL, price INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cp_tarif_code ON cp_tarif (code)');

        $this->addSql('CREATE TABLE cp_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, is_admin BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cp_user_phone ON cp_user (phone)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cp_user');
        $this->addSql('DROP TABLE cp_tarif');
        $this->addSql('DROP TABLE cp_owner_subscription');
        $this->addSql('DROP TABLE cp_deployment');
        $this->addSql('DROP TABLE cp_core_release');
        $this->addSql('DROP TABLE cp_server');
    }
}

