<?php
/**
 * ExternalMenuItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * ExternalMenuItem Class Doc Comment
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExternalMenuItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ExternalMenuItem';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'sku' => 'string',
        'name' => 'string',
        'description' => 'string',
        'allergens' => '\IIKO\Model\AllergenGroupDto3[]',
        'tags' => '\IIKO\Model\TagDto2[]',
        'labels' => '\IIKO\Model\LabelDto2[]',
        'item_sizes' => '\IIKO\Model\ExternalMenuItemSize[]',
        'item_id' => 'string',
        'modifier_schema_id' => 'string',
        'tax_category' => '\IIKO\Model\TaxCategoryDto3[]',
        'modifier_schema_name' => 'string',
        'type' => 'string',
        'can_be_divided' => 'Bool',
        'can_set_open_price' => 'bool',
        'use_balance_for_sell' => 'bool',
        'measure_unit' => 'string',
        'product_category_id' => 'string',
        'customer_tag_groups' => '\IIKO\Model\SelectedCustomerTag[]',
        'payment_subject' => 'string',
        'payment_subject_code' => 'string',
        'outer_ean_code' => 'string',
        'is_marked' => 'bool',
        'is_hidden' => 'bool',
        'barcodes' => '\IIKO\Model\BarcodeDto[]',
        'order_item_type' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'sku' => null,
        'name' => null,
        'description' => null,
        'allergens' => null,
        'tags' => null,
        'labels' => null,
        'item_sizes' => null,
        'item_id' => null,
        'modifier_schema_id' => null,
        'tax_category' => null,
        'modifier_schema_name' => null,
        'type' => null,
        'can_be_divided' => null,
        'can_set_open_price' => null,
        'use_balance_for_sell' => null,
        'measure_unit' => null,
        'product_category_id' => null,
        'customer_tag_groups' => null,
        'payment_subject' => null,
        'payment_subject_code' => null,
        'outer_ean_code' => null,
        'is_marked' => null,
        'is_hidden' => null,
        'barcodes' => null,
        'order_item_type' => 'enum'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'sku' => false,
        'name' => false,
        'description' => false,
        'allergens' => false,
        'tags' => false,
        'labels' => false,
        'item_sizes' => false,
        'item_id' => false,
        'modifier_schema_id' => false,
        'tax_category' => false,
        'modifier_schema_name' => true,
        'type' => false,
        'can_be_divided' => false,
        'can_set_open_price' => false,
        'use_balance_for_sell' => false,
        'measure_unit' => false,
        'product_category_id' => true,
        'customer_tag_groups' => false,
        'payment_subject' => true,
        'payment_subject_code' => true,
        'outer_ean_code' => true,
        'is_marked' => false,
        'is_hidden' => false,
        'barcodes' => true,
        'order_item_type' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sku' => 'sku',
        'name' => 'name',
        'description' => 'description',
        'allergens' => 'allergens',
        'tags' => 'tags',
        'labels' => 'labels',
        'item_sizes' => 'itemSizes',
        'item_id' => 'itemId',
        'modifier_schema_id' => 'modifierSchemaId',
        'tax_category' => 'taxCategory',
        'modifier_schema_name' => 'modifierSchemaName',
        'type' => 'type',
        'can_be_divided' => 'canBeDivided',
        'can_set_open_price' => 'canSetOpenPrice',
        'use_balance_for_sell' => 'useBalanceForSell',
        'measure_unit' => 'measureUnit',
        'product_category_id' => 'productCategoryId',
        'customer_tag_groups' => 'customerTagGroups',
        'payment_subject' => 'paymentSubject',
        'payment_subject_code' => 'paymentSubjectCode',
        'outer_ean_code' => 'outerEanCode',
        'is_marked' => 'isMarked',
        'is_hidden' => 'isHidden',
        'barcodes' => 'barcodes',
        'order_item_type' => 'orderItemType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sku' => 'setSku',
        'name' => 'setName',
        'description' => 'setDescription',
        'allergens' => 'setAllergens',
        'tags' => 'setTags',
        'labels' => 'setLabels',
        'item_sizes' => 'setItemSizes',
        'item_id' => 'setItemId',
        'modifier_schema_id' => 'setModifierSchemaId',
        'tax_category' => 'setTaxCategory',
        'modifier_schema_name' => 'setModifierSchemaName',
        'type' => 'setType',
        'can_be_divided' => 'setCanBeDivided',
        'can_set_open_price' => 'setCanSetOpenPrice',
        'use_balance_for_sell' => 'setUseBalanceForSell',
        'measure_unit' => 'setMeasureUnit',
        'product_category_id' => 'setProductCategoryId',
        'customer_tag_groups' => 'setCustomerTagGroups',
        'payment_subject' => 'setPaymentSubject',
        'payment_subject_code' => 'setPaymentSubjectCode',
        'outer_ean_code' => 'setOuterEanCode',
        'is_marked' => 'setIsMarked',
        'is_hidden' => 'setIsHidden',
        'barcodes' => 'setBarcodes',
        'order_item_type' => 'setOrderItemType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sku' => 'getSku',
        'name' => 'getName',
        'description' => 'getDescription',
        'allergens' => 'getAllergens',
        'tags' => 'getTags',
        'labels' => 'getLabels',
        'item_sizes' => 'getItemSizes',
        'item_id' => 'getItemId',
        'modifier_schema_id' => 'getModifierSchemaId',
        'tax_category' => 'getTaxCategory',
        'modifier_schema_name' => 'getModifierSchemaName',
        'type' => 'getType',
        'can_be_divided' => 'getCanBeDivided',
        'can_set_open_price' => 'getCanSetOpenPrice',
        'use_balance_for_sell' => 'getUseBalanceForSell',
        'measure_unit' => 'getMeasureUnit',
        'product_category_id' => 'getProductCategoryId',
        'customer_tag_groups' => 'getCustomerTagGroups',
        'payment_subject' => 'getPaymentSubject',
        'payment_subject_code' => 'getPaymentSubjectCode',
        'outer_ean_code' => 'getOuterEanCode',
        'is_marked' => 'getIsMarked',
        'is_hidden' => 'getIsHidden',
        'barcodes' => 'getBarcodes',
        'order_item_type' => 'getOrderItemType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_DISH = 'DISH';
    public const TYPE_COMBO = 'COMBO';
    public const ORDER_ITEM_TYPE_PRODUCT = 'Product';
    public const ORDER_ITEM_TYPE_COMPOUND = 'Compound';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_DISH,
            self::TYPE_COMBO,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOrderItemTypeAllowableValues()
    {
        return [
            self::ORDER_ITEM_TYPE_PRODUCT,
            self::ORDER_ITEM_TYPE_COMPOUND,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('sku', $data ?? [], '');
        $this->setIfExists('name', $data ?? [], '');
        $this->setIfExists('description', $data ?? [], '');
        $this->setIfExists('allergens', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('item_sizes', $data ?? [], null);
        $this->setIfExists('item_id', $data ?? [], '');
        $this->setIfExists('modifier_schema_id', $data ?? [], null);
        $this->setIfExists('tax_category', $data ?? [], null);
        $this->setIfExists('modifier_schema_name', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], 'DISH');
        $this->setIfExists('can_be_divided', $data ?? [], null);
        $this->setIfExists('can_set_open_price', $data ?? [], false);
        $this->setIfExists('use_balance_for_sell', $data ?? [], false);
        $this->setIfExists('measure_unit', $data ?? [], '');
        $this->setIfExists('product_category_id', $data ?? [], null);
        $this->setIfExists('customer_tag_groups', $data ?? [], null);
        $this->setIfExists('payment_subject', $data ?? [], null);
        $this->setIfExists('payment_subject_code', $data ?? [], null);
        $this->setIfExists('outer_ean_code', $data ?? [], null);
        $this->setIfExists('is_marked', $data ?? [], false);
        $this->setIfExists('is_hidden', $data ?? [], false);
        $this->setIfExists('barcodes', $data ?? [], null);
        $this->setIfExists('order_item_type', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['item_sizes'] === null) {
            $invalidProperties[] = "'item_sizes' can't be null";
        }
        if ($this->container['modifier_schema_id'] === null) {
            $invalidProperties[] = "'modifier_schema_id' can't be null";
        }
        if ($this->container['tax_category'] === null) {
            $invalidProperties[] = "'tax_category' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['order_item_type'] === null) {
            $invalidProperties[] = "'order_item_type' can't be null";
        }
        $allowedValues = $this->getOrderItemTypeAllowableValues();
        if (!is_null($this->container['order_item_type']) && !in_array($this->container['order_item_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'order_item_type', must be one of '%s'",
                $this->container['order_item_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sku
     *
     * @return string|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku Product code
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Product name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Product description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets allergens
     *
     * @return \IIKO\Model\AllergenGroupDto3[]|null
     */
    public function getAllergens()
    {
        return $this->container['allergens'];
    }

    /**
     * Sets allergens
     *
     * @param \IIKO\Model\AllergenGroupDto3[]|null $allergens Allergens
     *
     * @return self
     */
    public function setAllergens($allergens)
    {
        if (is_null($allergens)) {
            throw new \InvalidArgumentException('non-nullable allergens cannot be null');
        }
        $this->container['allergens'] = $allergens;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \IIKO\Model\TagDto2[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \IIKO\Model\TagDto2[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \IIKO\Model\LabelDto2[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \IIKO\Model\LabelDto2[]|null $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {
        if (is_null($labels)) {
            throw new \InvalidArgumentException('non-nullable labels cannot be null');
        }
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets item_sizes
     *
     * @return \IIKO\Model\ExternalMenuItemSize[]
     */
    public function getItemSizes()
    {
        return $this->container['item_sizes'];
    }

    /**
     * Sets item_sizes
     *
     * @param \IIKO\Model\ExternalMenuItemSize[] $item_sizes item_sizes
     *
     * @return self
     */
    public function setItemSizes($item_sizes)
    {
        if (is_null($item_sizes)) {
            throw new \InvalidArgumentException('non-nullable item_sizes cannot be null');
        }
        $this->container['item_sizes'] = $item_sizes;

        return $this;
    }

    /**
     * Gets item_id
     *
     * @return string|null
     */
    public function getItemId()
    {
        return $this->container['item_id'];
    }

    /**
     * Sets item_id
     *
     * @param string|null $item_id Product ID
     *
     * @return self
     */
    public function setItemId($item_id)
    {
        if (is_null($item_id)) {
            throw new \InvalidArgumentException('non-nullable item_id cannot be null');
        }
        $this->container['item_id'] = $item_id;

        return $this;
    }

    /**
     * Gets modifier_schema_id
     *
     * @return string
     */
    public function getModifierSchemaId()
    {
        return $this->container['modifier_schema_id'];
    }

    /**
     * Sets modifier_schema_id
     *
     * @param string $modifier_schema_id Modifier schema ID
     *
     * @return self
     */
    public function setModifierSchemaId($modifier_schema_id)
    {
        if (is_null($modifier_schema_id)) {
            throw new \InvalidArgumentException('non-nullable modifier_schema_id cannot be null');
        }
        $this->container['modifier_schema_id'] = $modifier_schema_id;

        return $this;
    }

    /**
     * Gets tax_category
     *
     * @return \IIKO\Model\TaxCategoryDto3[]
     */
    public function getTaxCategory()
    {
        return $this->container['tax_category'];
    }

    /**
     * Sets tax_category
     *
     * @param \IIKO\Model\TaxCategoryDto3[] $tax_category Tax category
     *
     * @return self
     */
    public function setTaxCategory($tax_category)
    {
        if (is_null($tax_category)) {
            throw new \InvalidArgumentException('non-nullable tax_category cannot be null');
        }
        $this->container['tax_category'] = $tax_category;

        return $this;
    }

    /**
     * Gets modifier_schema_name
     *
     * @return string|null
     */
    public function getModifierSchemaName()
    {
        return $this->container['modifier_schema_name'];
    }

    /**
     * Sets modifier_schema_name
     *
     * @param string|null $modifier_schema_name Modifier schema name
     *
     * @return self
     */
    public function setModifierSchemaName($modifier_schema_name)
    {
        if (is_null($modifier_schema_name)) {
            array_push($this->openAPINullablesSetToNull, 'modifier_schema_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('modifier_schema_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['modifier_schema_name'] = $modifier_schema_name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type Item type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets can_be_divided
     *
     * @return Bool|null
     */
    public function getCanBeDivided()
    {
        return $this->container['can_be_divided'];
    }

    /**
     * Sets can_be_divided
     *
     * @param Bool|null $can_be_divided can_be_divided
     *
     * @return self
     */
    public function setCanBeDivided($can_be_divided)
    {
        if (is_null($can_be_divided)) {
            throw new \InvalidArgumentException('non-nullable can_be_divided cannot be null');
        }
        $this->container['can_be_divided'] = $can_be_divided;

        return $this;
    }

    /**
     * Gets can_set_open_price
     *
     * @return bool|null
     */
    public function getCanSetOpenPrice()
    {
        return $this->container['can_set_open_price'];
    }

    /**
     * Sets can_set_open_price
     *
     * @param bool|null $can_set_open_price Can set open price flag
     *
     * @return self
     */
    public function setCanSetOpenPrice($can_set_open_price)
    {
        if (is_null($can_set_open_price)) {
            throw new \InvalidArgumentException('non-nullable can_set_open_price cannot be null');
        }
        $this->container['can_set_open_price'] = $can_set_open_price;

        return $this;
    }

    /**
     * Gets use_balance_for_sell
     *
     * @return bool|null
     */
    public function getUseBalanceForSell()
    {
        return $this->container['use_balance_for_sell'];
    }

    /**
     * Sets use_balance_for_sell
     *
     * @param bool|null $use_balance_for_sell use_balance_for_sell
     *
     * @return self
     */
    public function setUseBalanceForSell($use_balance_for_sell)
    {
        if (is_null($use_balance_for_sell)) {
            throw new \InvalidArgumentException('non-nullable use_balance_for_sell cannot be null');
        }
        $this->container['use_balance_for_sell'] = $use_balance_for_sell;

        return $this;
    }

    /**
     * Gets measure_unit
     *
     * @return string|null
     */
    public function getMeasureUnit()
    {
        return $this->container['measure_unit'];
    }

    /**
     * Sets measure_unit
     *
     * @param string|null $measure_unit Measure unit
     *
     * @return self
     */
    public function setMeasureUnit($measure_unit)
    {
        if (is_null($measure_unit)) {
            throw new \InvalidArgumentException('non-nullable measure_unit cannot be null');
        }
        $this->container['measure_unit'] = $measure_unit;

        return $this;
    }

    /**
     * Gets product_category_id
     *
     * @return string|null
     */
    public function getProductCategoryId()
    {
        return $this->container['product_category_id'];
    }

    /**
     * Sets product_category_id
     *
     * @param string|null $product_category_id Product category GUID
     *
     * @return self
     */
    public function setProductCategoryId($product_category_id)
    {
        if (is_null($product_category_id)) {
            array_push($this->openAPINullablesSetToNull, 'product_category_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_category_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['product_category_id'] = $product_category_id;

        return $this;
    }

    /**
     * Gets customer_tag_groups
     *
     * @return \IIKO\Model\SelectedCustomerTag[]|null
     */
    public function getCustomerTagGroups()
    {
        return $this->container['customer_tag_groups'];
    }

    /**
     * Sets customer_tag_groups
     *
     * @param \IIKO\Model\SelectedCustomerTag[]|null $customer_tag_groups customer_tag_groups
     *
     * @return self
     */
    public function setCustomerTagGroups($customer_tag_groups)
    {
        if (is_null($customer_tag_groups)) {
            throw new \InvalidArgumentException('non-nullable customer_tag_groups cannot be null');
        }
        $this->container['customer_tag_groups'] = $customer_tag_groups;

        return $this;
    }

    /**
     * Gets payment_subject
     *
     * @return string|null
     */
    public function getPaymentSubject()
    {
        return $this->container['payment_subject'];
    }

    /**
     * Sets payment_subject
     *
     * @param string|null $payment_subject payment_subject
     *
     * @return self
     */
    public function setPaymentSubject($payment_subject)
    {
        if (is_null($payment_subject)) {
            array_push($this->openAPINullablesSetToNull, 'payment_subject');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payment_subject', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payment_subject'] = $payment_subject;

        return $this;
    }

    /**
     * Gets payment_subject_code
     *
     * @return string|null
     */
    public function getPaymentSubjectCode()
    {
        return $this->container['payment_subject_code'];
    }

    /**
     * Sets payment_subject_code
     *
     * @param string|null $payment_subject_code payment_subject_code
     *
     * @return self
     */
    public function setPaymentSubjectCode($payment_subject_code)
    {
        if (is_null($payment_subject_code)) {
            array_push($this->openAPINullablesSetToNull, 'payment_subject_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payment_subject_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payment_subject_code'] = $payment_subject_code;

        return $this;
    }

    /**
     * Gets outer_ean_code
     *
     * @return string|null
     */
    public function getOuterEanCode()
    {
        return $this->container['outer_ean_code'];
    }

    /**
     * Sets outer_ean_code
     *
     * @param string|null $outer_ean_code outer_ean_code
     *
     * @return self
     */
    public function setOuterEanCode($outer_ean_code)
    {
        if (is_null($outer_ean_code)) {
            array_push($this->openAPINullablesSetToNull, 'outer_ean_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('outer_ean_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['outer_ean_code'] = $outer_ean_code;

        return $this;
    }

    /**
     * Gets is_marked
     *
     * @return bool|null
     */
    public function getIsMarked()
    {
        return $this->container['is_marked'];
    }

    /**
     * Sets is_marked
     *
     * @param bool|null $is_marked Marking flag
     *
     * @return self
     */
    public function setIsMarked($is_marked)
    {
        if (is_null($is_marked)) {
            throw new \InvalidArgumentException('non-nullable is_marked cannot be null');
        }
        $this->container['is_marked'] = $is_marked;

        return $this;
    }

    /**
     * Gets is_hidden
     *
     * @return bool|null
     */
    public function getIsHidden()
    {
        return $this->container['is_hidden'];
    }

    /**
     * Sets is_hidden
     *
     * @param bool|null $is_hidden Visibility flag
     *
     * @return self
     */
    public function setIsHidden($is_hidden)
    {
        if (is_null($is_hidden)) {
            throw new \InvalidArgumentException('non-nullable is_hidden cannot be null');
        }
        $this->container['is_hidden'] = $is_hidden;

        return $this;
    }

    /**
     * Gets barcodes
     *
     * @return \IIKO\Model\BarcodeDto[]|null
     */
    public function getBarcodes()
    {
        return $this->container['barcodes'];
    }

    /**
     * Sets barcodes
     *
     * @param \IIKO\Model\BarcodeDto[]|null $barcodes barcodes
     *
     * @return self
     */
    public function setBarcodes($barcodes)
    {
        if (is_null($barcodes)) {
            array_push($this->openAPINullablesSetToNull, 'barcodes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('barcodes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['barcodes'] = $barcodes;

        return $this;
    }

    /**
     * Gets order_item_type
     *
     * @return string
     */
    public function getOrderItemType()
    {
        return $this->container['order_item_type'];
    }

    /**
     * Sets order_item_type
     *
     * @param string $order_item_type Product or compound. Depends on modifiers scheme existence
     *
     * @return self
     */
    public function setOrderItemType($order_item_type)
    {
        if (is_null($order_item_type)) {
            throw new \InvalidArgumentException('non-nullable order_item_type cannot be null');
        }
        $allowedValues = $this->getOrderItemTypeAllowableValues();
        if (!in_array($order_item_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'order_item_type', must be one of '%s'",
                    $order_item_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['order_item_type'] = $order_item_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


