<?php
/**
 * IikoTransportPublicApiContractsReservesSectionSchema
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * IikoTransportPublicApiContractsReservesSectionSchema Class Doc Comment
 *
 * @category Class
 * @description Table layout.
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IikoTransportPublicApiContractsReservesSectionSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'iikoTransport.PublicApi.Contracts.Reserves.SectionSchema';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'width' => 'int',
        'height' => 'int',
        'mark_elements' => '\IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionMark[]',
        'table_elements' => '\IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionTable[]',
        'rectangle_elements' => '\IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionEllipse[]',
        'ellipse_elements' => '\IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionEllipse[]',
        'revision' => 'int',
        'is_deleted' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'width' => 'int32',
        'height' => 'int32',
        'mark_elements' => null,
        'table_elements' => null,
        'rectangle_elements' => null,
        'ellipse_elements' => null,
        'revision' => 'int64',
        'is_deleted' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'width' => false,
        'height' => false,
        'mark_elements' => false,
        'table_elements' => false,
        'rectangle_elements' => false,
        'ellipse_elements' => false,
        'revision' => false,
        'is_deleted' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'width' => 'width',
        'height' => 'height',
        'mark_elements' => 'markElements',
        'table_elements' => 'tableElements',
        'rectangle_elements' => 'rectangleElements',
        'ellipse_elements' => 'ellipseElements',
        'revision' => 'revision',
        'is_deleted' => 'isDeleted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'width' => 'setWidth',
        'height' => 'setHeight',
        'mark_elements' => 'setMarkElements',
        'table_elements' => 'setTableElements',
        'rectangle_elements' => 'setRectangleElements',
        'ellipse_elements' => 'setEllipseElements',
        'revision' => 'setRevision',
        'is_deleted' => 'setIsDeleted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'width' => 'getWidth',
        'height' => 'getHeight',
        'mark_elements' => 'getMarkElements',
        'table_elements' => 'getTableElements',
        'rectangle_elements' => 'getRectangleElements',
        'ellipse_elements' => 'getEllipseElements',
        'revision' => 'getRevision',
        'is_deleted' => 'getIsDeleted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('width', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('mark_elements', $data ?? [], null);
        $this->setIfExists('table_elements', $data ?? [], null);
        $this->setIfExists('rectangle_elements', $data ?? [], null);
        $this->setIfExists('ellipse_elements', $data ?? [], null);
        $this->setIfExists('revision', $data ?? [], null);
        $this->setIfExists('is_deleted', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['width'] === null) {
            $invalidProperties[] = "'width' can't be null";
        }
        if ($this->container['height'] === null) {
            $invalidProperties[] = "'height' can't be null";
        }
        if ($this->container['mark_elements'] === null) {
            $invalidProperties[] = "'mark_elements' can't be null";
        }
        if ($this->container['table_elements'] === null) {
            $invalidProperties[] = "'table_elements' can't be null";
        }
        if ($this->container['rectangle_elements'] === null) {
            $invalidProperties[] = "'rectangle_elements' can't be null";
        }
        if ($this->container['ellipse_elements'] === null) {
            $invalidProperties[] = "'ellipse_elements' can't be null";
        }
        if ($this->container['revision'] === null) {
            $invalidProperties[] = "'revision' can't be null";
        }
        if ($this->container['is_deleted'] === null) {
            $invalidProperties[] = "'is_deleted' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets width
     *
     * @return int
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param int $width Layout width in px.
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            throw new \InvalidArgumentException('non-nullable width cannot be null');
        }
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return int
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param int $height Layout height in px.
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            throw new \InvalidArgumentException('non-nullable height cannot be null');
        }
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets mark_elements
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionMark[]
     */
    public function getMarkElements()
    {
        return $this->container['mark_elements'];
    }

    /**
     * Sets mark_elements
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionMark[] $mark_elements Collection of restaurant section marks.
     *
     * @return self
     */
    public function setMarkElements($mark_elements)
    {
        if (is_null($mark_elements)) {
            throw new \InvalidArgumentException('non-nullable mark_elements cannot be null');
        }
        $this->container['mark_elements'] = $mark_elements;

        return $this;
    }

    /**
     * Gets table_elements
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionTable[]
     */
    public function getTableElements()
    {
        return $this->container['table_elements'];
    }

    /**
     * Sets table_elements
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionTable[] $table_elements Collection of restaurant section tables.
     *
     * @return self
     */
    public function setTableElements($table_elements)
    {
        if (is_null($table_elements)) {
            throw new \InvalidArgumentException('non-nullable table_elements cannot be null');
        }
        $this->container['table_elements'] = $table_elements;

        return $this;
    }

    /**
     * Gets rectangle_elements
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionEllipse[]
     */
    public function getRectangleElements()
    {
        return $this->container['rectangle_elements'];
    }

    /**
     * Sets rectangle_elements
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionEllipse[] $rectangle_elements Collection of restaurant section rectangles.
     *
     * @return self
     */
    public function setRectangleElements($rectangle_elements)
    {
        if (is_null($rectangle_elements)) {
            throw new \InvalidArgumentException('non-nullable rectangle_elements cannot be null');
        }
        $this->container['rectangle_elements'] = $rectangle_elements;

        return $this;
    }

    /**
     * Gets ellipse_elements
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionEllipse[]
     */
    public function getEllipseElements()
    {
        return $this->container['ellipse_elements'];
    }

    /**
     * Sets ellipse_elements
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsReservesRestaurantSectionEllipse[] $ellipse_elements Collection of restaurant section ellipses.
     *
     * @return self
     */
    public function setEllipseElements($ellipse_elements)
    {
        if (is_null($ellipse_elements)) {
            throw new \InvalidArgumentException('non-nullable ellipse_elements cannot be null');
        }
        $this->container['ellipse_elements'] = $ellipse_elements;

        return $this;
    }

    /**
     * Gets revision
     *
     * @return int
     */
    public function getRevision()
    {
        return $this->container['revision'];
    }

    /**
     * Sets revision
     *
     * @param int $revision Last modified time.
     *
     * @return self
     */
    public function setRevision($revision)
    {
        if (is_null($revision)) {
            throw new \InvalidArgumentException('non-nullable revision cannot be null');
        }
        $this->container['revision'] = $revision;

        return $this;
    }

    /**
     * Gets is_deleted
     *
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->container['is_deleted'];
    }

    /**
     * Sets is_deleted
     *
     * @param bool $is_deleted Is schema deleted.
     *
     * @return self
     */
    public function setIsDeleted($is_deleted)
    {
        if (is_null($is_deleted)) {
            throw new \InvalidArgumentException('non-nullable is_deleted cannot be null');
        }
        $this->container['is_deleted'] = $is_deleted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


