<?php
/**
 * IikoTransportPublicApiContractsOrganizationsOrganizationSettings
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * IikoTransportPublicApiContractsOrganizationsOrganizationSettings Class Doc Comment
 *
 * @category Class
 * @description Organization settings.
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IikoTransportPublicApiContractsOrganizationsOrganizationSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'iikoTransport.PublicApi.Contracts.Organizations.OrganizationSettings';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'prices_vat_inclusive' => 'bool',
        'loyalty_discount_affects_vat' => 'bool',
        'version' => 'string',
        'address_format_type' => '\IIKO\Model\IikoTransportPublicApiContractsOrganizationsAddressFormatType',
        'is_anonymous_guests_allowed' => 'bool',
        'name' => 'string',
        'country' => 'string',
        'restaurant_address' => 'string',
        'latitude' => 'float',
        'longitude' => 'float',
        'use_uae_addressing_system' => 'bool',
        'country_phone_code' => 'string',
        'marketing_source_required_in_delivery' => 'bool',
        'default_delivery_city_id' => 'string',
        'delivery_city_ids' => 'string[]',
        'delivery_service_type' => '\IIKO\Model\IikoTransportPublicApiContractsOrganizationsDeliverySettingsServiceType',
        'delivery_order_payment_settings' => '\IIKO\Model\IikoTransportPublicApiContractsOrganizationsDeliveryOrderPaymentSettings',
        'default_call_center_payment_type_id' => 'string',
        'order_item_comment_enabled' => 'bool',
        'is_confirmation_enabled' => 'bool',
        'confirm_allowed_interval_in_minutes' => 'int',
        'address_lookup' => '\IIKO\Model\IikoTransportPublicApiContractsAddressHintsAddressHintsServiceType[]',
        'use_business_hours_and_mapping' => 'bool',
        'currency_iso_name' => 'string',
        'external_data' => '\IIKO\Model\IikoTransportPublicApiContractsCommonExternalData[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'prices_vat_inclusive' => null,
        'loyalty_discount_affects_vat' => null,
        'version' => null,
        'address_format_type' => null,
        'is_anonymous_guests_allowed' => null,
        'name' => null,
        'country' => null,
        'restaurant_address' => null,
        'latitude' => 'double',
        'longitude' => 'double',
        'use_uae_addressing_system' => null,
        'country_phone_code' => null,
        'marketing_source_required_in_delivery' => null,
        'default_delivery_city_id' => 'uuid',
        'delivery_city_ids' => 'uuid',
        'delivery_service_type' => null,
        'delivery_order_payment_settings' => null,
        'default_call_center_payment_type_id' => 'uuid',
        'order_item_comment_enabled' => null,
        'is_confirmation_enabled' => null,
        'confirm_allowed_interval_in_minutes' => 'int32',
        'address_lookup' => null,
        'use_business_hours_and_mapping' => null,
        'currency_iso_name' => null,
        'external_data' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'prices_vat_inclusive' => true,
        'loyalty_discount_affects_vat' => true,
        'version' => true,
        'address_format_type' => true,
        'is_anonymous_guests_allowed' => true,
        'name' => true,
        'country' => true,
        'restaurant_address' => true,
        'latitude' => true,
        'longitude' => true,
        'use_uae_addressing_system' => true,
        'country_phone_code' => true,
        'marketing_source_required_in_delivery' => true,
        'default_delivery_city_id' => true,
        'delivery_city_ids' => true,
        'delivery_service_type' => true,
        'delivery_order_payment_settings' => true,
        'default_call_center_payment_type_id' => true,
        'order_item_comment_enabled' => true,
        'is_confirmation_enabled' => true,
        'confirm_allowed_interval_in_minutes' => true,
        'address_lookup' => true,
        'use_business_hours_and_mapping' => true,
        'currency_iso_name' => true,
        'external_data' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'prices_vat_inclusive' => 'pricesVatInclusive',
        'loyalty_discount_affects_vat' => 'loyaltyDiscountAffectsVat',
        'version' => 'version',
        'address_format_type' => 'addressFormatType',
        'is_anonymous_guests_allowed' => 'isAnonymousGuestsAllowed',
        'name' => 'name',
        'country' => 'country',
        'restaurant_address' => 'restaurantAddress',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'use_uae_addressing_system' => 'useUaeAddressingSystem',
        'country_phone_code' => 'countryPhoneCode',
        'marketing_source_required_in_delivery' => 'marketingSourceRequiredInDelivery',
        'default_delivery_city_id' => 'defaultDeliveryCityId',
        'delivery_city_ids' => 'deliveryCityIds',
        'delivery_service_type' => 'deliveryServiceType',
        'delivery_order_payment_settings' => 'deliveryOrderPaymentSettings',
        'default_call_center_payment_type_id' => 'defaultCallCenterPaymentTypeId',
        'order_item_comment_enabled' => 'orderItemCommentEnabled',
        'is_confirmation_enabled' => 'isConfirmationEnabled',
        'confirm_allowed_interval_in_minutes' => 'confirmAllowedIntervalInMinutes',
        'address_lookup' => 'addressLookup',
        'use_business_hours_and_mapping' => 'useBusinessHoursAndMapping',
        'currency_iso_name' => 'currencyIsoName',
        'external_data' => 'externalData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'prices_vat_inclusive' => 'setPricesVatInclusive',
        'loyalty_discount_affects_vat' => 'setLoyaltyDiscountAffectsVat',
        'version' => 'setVersion',
        'address_format_type' => 'setAddressFormatType',
        'is_anonymous_guests_allowed' => 'setIsAnonymousGuestsAllowed',
        'name' => 'setName',
        'country' => 'setCountry',
        'restaurant_address' => 'setRestaurantAddress',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'use_uae_addressing_system' => 'setUseUaeAddressingSystem',
        'country_phone_code' => 'setCountryPhoneCode',
        'marketing_source_required_in_delivery' => 'setMarketingSourceRequiredInDelivery',
        'default_delivery_city_id' => 'setDefaultDeliveryCityId',
        'delivery_city_ids' => 'setDeliveryCityIds',
        'delivery_service_type' => 'setDeliveryServiceType',
        'delivery_order_payment_settings' => 'setDeliveryOrderPaymentSettings',
        'default_call_center_payment_type_id' => 'setDefaultCallCenterPaymentTypeId',
        'order_item_comment_enabled' => 'setOrderItemCommentEnabled',
        'is_confirmation_enabled' => 'setIsConfirmationEnabled',
        'confirm_allowed_interval_in_minutes' => 'setConfirmAllowedIntervalInMinutes',
        'address_lookup' => 'setAddressLookup',
        'use_business_hours_and_mapping' => 'setUseBusinessHoursAndMapping',
        'currency_iso_name' => 'setCurrencyIsoName',
        'external_data' => 'setExternalData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'prices_vat_inclusive' => 'getPricesVatInclusive',
        'loyalty_discount_affects_vat' => 'getLoyaltyDiscountAffectsVat',
        'version' => 'getVersion',
        'address_format_type' => 'getAddressFormatType',
        'is_anonymous_guests_allowed' => 'getIsAnonymousGuestsAllowed',
        'name' => 'getName',
        'country' => 'getCountry',
        'restaurant_address' => 'getRestaurantAddress',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'use_uae_addressing_system' => 'getUseUaeAddressingSystem',
        'country_phone_code' => 'getCountryPhoneCode',
        'marketing_source_required_in_delivery' => 'getMarketingSourceRequiredInDelivery',
        'default_delivery_city_id' => 'getDefaultDeliveryCityId',
        'delivery_city_ids' => 'getDeliveryCityIds',
        'delivery_service_type' => 'getDeliveryServiceType',
        'delivery_order_payment_settings' => 'getDeliveryOrderPaymentSettings',
        'default_call_center_payment_type_id' => 'getDefaultCallCenterPaymentTypeId',
        'order_item_comment_enabled' => 'getOrderItemCommentEnabled',
        'is_confirmation_enabled' => 'getIsConfirmationEnabled',
        'confirm_allowed_interval_in_minutes' => 'getConfirmAllowedIntervalInMinutes',
        'address_lookup' => 'getAddressLookup',
        'use_business_hours_and_mapping' => 'getUseBusinessHoursAndMapping',
        'currency_iso_name' => 'getCurrencyIsoName',
        'external_data' => 'getExternalData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('prices_vat_inclusive', $data ?? [], null);
        $this->setIfExists('loyalty_discount_affects_vat', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('address_format_type', $data ?? [], null);
        $this->setIfExists('is_anonymous_guests_allowed', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('restaurant_address', $data ?? [], null);
        $this->setIfExists('latitude', $data ?? [], null);
        $this->setIfExists('longitude', $data ?? [], null);
        $this->setIfExists('use_uae_addressing_system', $data ?? [], null);
        $this->setIfExists('country_phone_code', $data ?? [], null);
        $this->setIfExists('marketing_source_required_in_delivery', $data ?? [], null);
        $this->setIfExists('default_delivery_city_id', $data ?? [], null);
        $this->setIfExists('delivery_city_ids', $data ?? [], null);
        $this->setIfExists('delivery_service_type', $data ?? [], null);
        $this->setIfExists('delivery_order_payment_settings', $data ?? [], null);
        $this->setIfExists('default_call_center_payment_type_id', $data ?? [], null);
        $this->setIfExists('order_item_comment_enabled', $data ?? [], null);
        $this->setIfExists('is_confirmation_enabled', $data ?? [], null);
        $this->setIfExists('confirm_allowed_interval_in_minutes', $data ?? [], null);
        $this->setIfExists('address_lookup', $data ?? [], null);
        $this->setIfExists('use_business_hours_and_mapping', $data ?? [], null);
        $this->setIfExists('currency_iso_name', $data ?? [], null);
        $this->setIfExists('external_data', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Organization ID.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets prices_vat_inclusive
     *
     * @return bool|null
     */
    public function getPricesVatInclusive()
    {
        return $this->container['prices_vat_inclusive'];
    }

    /**
     * Sets prices_vat_inclusive
     *
     * @param bool|null $prices_vat_inclusive Determines whether organization prices include VAT.                Available if `VAT` requested.
     *
     * @return self
     */
    public function setPricesVatInclusive($prices_vat_inclusive)
    {
        if (is_null($prices_vat_inclusive)) {
            array_push($this->openAPINullablesSetToNull, 'prices_vat_inclusive');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('prices_vat_inclusive', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['prices_vat_inclusive'] = $prices_vat_inclusive;

        return $this;
    }

    /**
     * Gets loyalty_discount_affects_vat
     *
     * @return bool|null
     */
    public function getLoyaltyDiscountAffectsVat()
    {
        return $this->container['loyalty_discount_affects_vat'];
    }

    /**
     * Sets loyalty_discount_affects_vat
     *
     * @param bool|null $loyalty_discount_affects_vat Determines whether organization loyalty discounts affects VAT.                > Working only if \"pricesVatInclusive\" = false                Available if `VAT` requested.
     *
     * @return self
     */
    public function setLoyaltyDiscountAffectsVat($loyalty_discount_affects_vat)
    {
        if (is_null($loyalty_discount_affects_vat)) {
            array_push($this->openAPINullablesSetToNull, 'loyalty_discount_affects_vat');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('loyalty_discount_affects_vat', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['loyalty_discount_affects_vat'] = $loyalty_discount_affects_vat;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string|null $version RMS version.                Available if `Version` requested.
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            array_push($this->openAPINullablesSetToNull, 'version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('version', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets address_format_type
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsOrganizationsAddressFormatType|null
     */
    public function getAddressFormatType()
    {
        return $this->container['address_format_type'];
    }

    /**
     * Sets address_format_type
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsOrganizationsAddressFormatType|null $address_format_type Address format type.                Available if `AddressFormatType` requested.
     *
     * @return self
     */
    public function setAddressFormatType($address_format_type)
    {
        if (is_null($address_format_type)) {
            array_push($this->openAPINullablesSetToNull, 'address_format_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('address_format_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['address_format_type'] = $address_format_type;

        return $this;
    }

    /**
     * Gets is_anonymous_guests_allowed
     *
     * @return bool|null
     */
    public function getIsAnonymousGuestsAllowed()
    {
        return $this->container['is_anonymous_guests_allowed'];
    }

    /**
     * Sets is_anonymous_guests_allowed
     *
     * @param bool|null $is_anonymous_guests_allowed If the store allows orders for anonymous guests, then it is not necessary to transfer  information about the guest as part of the delivery order. You can only transfer  the phone number and optionally name of the guest, which will not be stored in the guest base  and will only be used for the delivery of a current delivery order.                Available if `IsAnonymousGuestsAllowed` requested.
     *
     * @return self
     */
    public function setIsAnonymousGuestsAllowed($is_anonymous_guests_allowed)
    {
        if (is_null($is_anonymous_guests_allowed)) {
            array_push($this->openAPINullablesSetToNull, 'is_anonymous_guests_allowed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_anonymous_guests_allowed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_anonymous_guests_allowed'] = $is_anonymous_guests_allowed;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Organization name.                Available if `Name` requested.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Country.                Available if `Country` requested.
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            array_push($this->openAPINullablesSetToNull, 'country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets restaurant_address
     *
     * @return string|null
     */
    public function getRestaurantAddress()
    {
        return $this->container['restaurant_address'];
    }

    /**
     * Sets restaurant_address
     *
     * @param string|null $restaurant_address Restaurant address.                Available if `RestaurantAddress` requested.
     *
     * @return self
     */
    public function setRestaurantAddress($restaurant_address)
    {
        if (is_null($restaurant_address)) {
            array_push($this->openAPINullablesSetToNull, 'restaurant_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('restaurant_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['restaurant_address'] = $restaurant_address;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return float|null
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param float|null $latitude Latitude.                Available if `Latitude` requested.
     *
     * @return self
     */
    public function setLatitude($latitude)
    {
        if (is_null($latitude)) {
            array_push($this->openAPINullablesSetToNull, 'latitude');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('latitude', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return float|null
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param float|null $longitude Longitude.                Available if `Longitude` requested.
     *
     * @return self
     */
    public function setLongitude($longitude)
    {
        if (is_null($longitude)) {
            array_push($this->openAPINullablesSetToNull, 'longitude');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('longitude', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets use_uae_addressing_system
     *
     * @return bool|null
     */
    public function getUseUaeAddressingSystem()
    {
        return $this->container['use_uae_addressing_system'];
    }

    /**
     * Sets use_uae_addressing_system
     *
     * @param bool|null $use_uae_addressing_system Regional setting \"Use the UAE Addressing System\".                Available if `UseUaeAddressingSystem` requested.
     *
     * @return self
     */
    public function setUseUaeAddressingSystem($use_uae_addressing_system)
    {
        if (is_null($use_uae_addressing_system)) {
            array_push($this->openAPINullablesSetToNull, 'use_uae_addressing_system');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('use_uae_addressing_system', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['use_uae_addressing_system'] = $use_uae_addressing_system;

        return $this;
    }

    /**
     * Gets country_phone_code
     *
     * @return string|null
     */
    public function getCountryPhoneCode()
    {
        return $this->container['country_phone_code'];
    }

    /**
     * Sets country_phone_code
     *
     * @param string|null $country_phone_code Country dialing code.                Available if `CountryPhoneCode` requested.
     *
     * @return self
     */
    public function setCountryPhoneCode($country_phone_code)
    {
        if (is_null($country_phone_code)) {
            array_push($this->openAPINullablesSetToNull, 'country_phone_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country_phone_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country_phone_code'] = $country_phone_code;

        return $this;
    }

    /**
     * Gets marketing_source_required_in_delivery
     *
     * @return bool|null
     */
    public function getMarketingSourceRequiredInDelivery()
    {
        return $this->container['marketing_source_required_in_delivery'];
    }

    /**
     * Sets marketing_source_required_in_delivery
     *
     * @param bool|null $marketing_source_required_in_delivery Require mandatory marketing source input when creating a delivery.                Available if `MarketingSourceRequiredInDelivery` requested.
     *
     * @return self
     */
    public function setMarketingSourceRequiredInDelivery($marketing_source_required_in_delivery)
    {
        if (is_null($marketing_source_required_in_delivery)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_source_required_in_delivery');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_source_required_in_delivery', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_source_required_in_delivery'] = $marketing_source_required_in_delivery;

        return $this;
    }

    /**
     * Gets default_delivery_city_id
     *
     * @return string|null
     */
    public function getDefaultDeliveryCityId()
    {
        return $this->container['default_delivery_city_id'];
    }

    /**
     * Sets default_delivery_city_id
     *
     * @param string|null $default_delivery_city_id Default delivery city.                Available if `DefaultDeliveryCityId` requested.
     *
     * @return self
     */
    public function setDefaultDeliveryCityId($default_delivery_city_id)
    {
        if (is_null($default_delivery_city_id)) {
            array_push($this->openAPINullablesSetToNull, 'default_delivery_city_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_delivery_city_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_delivery_city_id'] = $default_delivery_city_id;

        return $this;
    }

    /**
     * Gets delivery_city_ids
     *
     * @return string[]|null
     */
    public function getDeliveryCityIds()
    {
        return $this->container['delivery_city_ids'];
    }

    /**
     * Sets delivery_city_ids
     *
     * @param string[]|null $delivery_city_ids Delivery cities.                Available if `DeliveryCityIds` requested.
     *
     * @return self
     */
    public function setDeliveryCityIds($delivery_city_ids)
    {
        if (is_null($delivery_city_ids)) {
            array_push($this->openAPINullablesSetToNull, 'delivery_city_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delivery_city_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delivery_city_ids'] = $delivery_city_ids;

        return $this;
    }

    /**
     * Gets delivery_service_type
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsOrganizationsDeliverySettingsServiceType|null
     */
    public function getDeliveryServiceType()
    {
        return $this->container['delivery_service_type'];
    }

    /**
     * Sets delivery_service_type
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsOrganizationsDeliverySettingsServiceType|null $delivery_service_type Delivery type.                Available if `DeliveryServiceType` requested.
     *
     * @return self
     */
    public function setDeliveryServiceType($delivery_service_type)
    {
        if (is_null($delivery_service_type)) {
            array_push($this->openAPINullablesSetToNull, 'delivery_service_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delivery_service_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delivery_service_type'] = $delivery_service_type;

        return $this;
    }

    /**
     * Gets delivery_order_payment_settings
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsOrganizationsDeliveryOrderPaymentSettings|null
     */
    public function getDeliveryOrderPaymentSettings()
    {
        return $this->container['delivery_order_payment_settings'];
    }

    /**
     * Sets delivery_order_payment_settings
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsOrganizationsDeliveryOrderPaymentSettings|null $delivery_order_payment_settings Delivery order payment settings.                Available if `DeliveryOrderPaymentSettings` requested.
     *
     * @return self
     */
    public function setDeliveryOrderPaymentSettings($delivery_order_payment_settings)
    {
        if (is_null($delivery_order_payment_settings)) {
            array_push($this->openAPINullablesSetToNull, 'delivery_order_payment_settings');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delivery_order_payment_settings', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delivery_order_payment_settings'] = $delivery_order_payment_settings;

        return $this;
    }

    /**
     * Gets default_call_center_payment_type_id
     *
     * @return string|null
     */
    public function getDefaultCallCenterPaymentTypeId()
    {
        return $this->container['default_call_center_payment_type_id'];
    }

    /**
     * Sets default_call_center_payment_type_id
     *
     * @param string|null $default_call_center_payment_type_id Default payment type for CallCenter.                Available if `DefaultCallCenterPaymentTypeId` requested.
     *
     * @return self
     */
    public function setDefaultCallCenterPaymentTypeId($default_call_center_payment_type_id)
    {
        if (is_null($default_call_center_payment_type_id)) {
            array_push($this->openAPINullablesSetToNull, 'default_call_center_payment_type_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_call_center_payment_type_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_call_center_payment_type_id'] = $default_call_center_payment_type_id;

        return $this;
    }

    /**
     * Gets order_item_comment_enabled
     *
     * @return bool|null
     */
    public function getOrderItemCommentEnabled()
    {
        return $this->container['order_item_comment_enabled'];
    }

    /**
     * Sets order_item_comment_enabled
     *
     * @param bool|null $order_item_comment_enabled Allow text comments for order items (in all restaurant sections).                Available if `OrderItemCommentEnabled` requested.
     *
     * @return self
     */
    public function setOrderItemCommentEnabled($order_item_comment_enabled)
    {
        if (is_null($order_item_comment_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'order_item_comment_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_item_comment_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_item_comment_enabled'] = $order_item_comment_enabled;

        return $this;
    }

    /**
     * Gets is_confirmation_enabled
     *
     * @return bool|null
     */
    public function getIsConfirmationEnabled()
    {
        return $this->container['is_confirmation_enabled'];
    }

    /**
     * Sets is_confirmation_enabled
     *
     * @param bool|null $is_confirmation_enabled Determines whether to use delivery confirmation.                Available if `IsConfirmationEnabled` requested.
     *
     * @return self
     */
    public function setIsConfirmationEnabled($is_confirmation_enabled)
    {
        if (is_null($is_confirmation_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'is_confirmation_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_confirmation_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_confirmation_enabled'] = $is_confirmation_enabled;

        return $this;
    }

    /**
     * Gets confirm_allowed_interval_in_minutes
     *
     * @return int|null
     */
    public function getConfirmAllowedIntervalInMinutes()
    {
        return $this->container['confirm_allowed_interval_in_minutes'];
    }

    /**
     * Sets confirm_allowed_interval_in_minutes
     *
     * @param int|null $confirm_allowed_interval_in_minutes Confirm orders time interval.                Available if `ConfirmAllowedIntervalInMinutes` requested.
     *
     * @return self
     */
    public function setConfirmAllowedIntervalInMinutes($confirm_allowed_interval_in_minutes)
    {
        if (is_null($confirm_allowed_interval_in_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'confirm_allowed_interval_in_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('confirm_allowed_interval_in_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['confirm_allowed_interval_in_minutes'] = $confirm_allowed_interval_in_minutes;

        return $this;
    }

    /**
     * Gets address_lookup
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsAddressHintsAddressHintsServiceType[]|null
     */
    public function getAddressLookup()
    {
        return $this->container['address_lookup'];
    }

    /**
     * Sets address_lookup
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsAddressHintsAddressHintsServiceType[]|null $address_lookup Available address lookup services.                Available if `AddressLookup` requested.
     *
     * @return self
     */
    public function setAddressLookup($address_lookup)
    {
        if (is_null($address_lookup)) {
            array_push($this->openAPINullablesSetToNull, 'address_lookup');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('address_lookup', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['address_lookup'] = $address_lookup;

        return $this;
    }

    /**
     * Gets use_business_hours_and_mapping
     *
     * @return bool|null
     */
    public function getUseBusinessHoursAndMapping()
    {
        return $this->container['use_business_hours_and_mapping'];
    }

    /**
     * Sets use_business_hours_and_mapping
     *
     * @param bool|null $use_business_hours_and_mapping Determines whether the organization use a business hours and mapping settings.
     *
     * @return self
     */
    public function setUseBusinessHoursAndMapping($use_business_hours_and_mapping)
    {
        if (is_null($use_business_hours_and_mapping)) {
            array_push($this->openAPINullablesSetToNull, 'use_business_hours_and_mapping');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('use_business_hours_and_mapping', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['use_business_hours_and_mapping'] = $use_business_hours_and_mapping;

        return $this;
    }

    /**
     * Gets currency_iso_name
     *
     * @return string|null
     */
    public function getCurrencyIsoName()
    {
        return $this->container['currency_iso_name'];
    }

    /**
     * Sets currency_iso_name
     *
     * @param string|null $currency_iso_name ISO currency code (for example: RUB, USD, EUR).
     *
     * @return self
     */
    public function setCurrencyIsoName($currency_iso_name)
    {
        if (is_null($currency_iso_name)) {
            array_push($this->openAPINullablesSetToNull, 'currency_iso_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('currency_iso_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['currency_iso_name'] = $currency_iso_name;

        return $this;
    }

    /**
     * Gets external_data
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsCommonExternalData[]|null
     */
    public function getExternalData()
    {
        return $this->container['external_data'];
    }

    /**
     * Sets external_data
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsCommonExternalData[]|null $external_data Organization`s external data.
     *
     * @return self
     */
    public function setExternalData($external_data)
    {
        if (is_null($external_data)) {
            array_push($this->openAPINullablesSetToNull, 'external_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_data'] = $external_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


