<?php
/**
 * IikoTransportPublicApiContractsWebHooksWebHookEventType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;
use \IIKO\ObjectSerializer;

/**
 * IikoTransportPublicApiContractsWebHooksWebHookEventType Class Doc Comment
 *
 * @category Class
 * @description Types of events which can be notified by a webhook.
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IikoTransportPublicApiContractsWebHooksWebHookEventType
{
    /**
     * Possible values of this enum
     */
    public const DELIVERY_ORDER_UPDATE = 'DeliveryOrderUpdate';

    public const DELIVERY_ORDER_ERROR = 'DeliveryOrderError';

    public const RESERVE_UPDATE = 'ReserveUpdate';

    public const RESERVE_ERROR = 'ReserveError';

    public const TABLE_ORDER_UPDATE = 'TableOrderUpdate';

    public const TABLE_ORDER_ERROR = 'TableOrderError';

    public const STOP_LIST_UPDATE = 'StopListUpdate';

    public const PERSONAL_SHIFT = 'PersonalShift';

    public const KITCHEN_ORDER_UPDATE = 'KitchenOrderUpdate';

    public const NOMENCLATURE_UPDATE = 'NomenclatureUpdate';

    public const BUSINESS_HOURS_AND_MAPPING_UPDATE = 'BusinessHoursAndMappingUpdate';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DELIVERY_ORDER_UPDATE,
            self::DELIVERY_ORDER_ERROR,
            self::RESERVE_UPDATE,
            self::RESERVE_ERROR,
            self::TABLE_ORDER_UPDATE,
            self::TABLE_ORDER_ERROR,
            self::STOP_LIST_UPDATE,
            self::PERSONAL_SHIFT,
            self::KITCHEN_ORDER_UPDATE,
            self::NOMENCLATURE_UPDATE,
            self::BUSINESS_HOURS_AND_MAPPING_UPDATE
        ];
    }
}


