<?php
/**
 * IikoTransportPublicApiContractsDeliveriesResponseOrderProductOrderItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;
use \IIKO\ObjectSerializer;

/**
 * IikoTransportPublicApiContractsDeliveriesResponseOrderProductOrderItem Class Doc Comment
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IikoTransportPublicApiContractsDeliveriesResponseOrderProductOrderItem extends IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItem
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.ProductOrderItem';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'product' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderCancelCause',
        'modifiers' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemModifier[]',
        'codes' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemIdentifierCode[][]',
        'price' => 'float',
        'cost' => 'float',
        'price_predefined' => 'bool',
        'position_id' => 'string',
        'tax_percent' => 'float',
        'result_sum' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'product' => null,
        'modifiers' => null,
        'codes' => null,
        'price' => 'double',
        'cost' => 'double',
        'price_predefined' => null,
        'position_id' => 'uuid',
        'tax_percent' => 'double',
        'result_sum' => 'double'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'product' => false,
        'modifiers' => true,
        'codes' => true,
        'price' => false,
        'cost' => false,
        'price_predefined' => false,
        'position_id' => true,
        'tax_percent' => true,
        'result_sum' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables + parent::openAPINullables();
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'product' => 'product',
        'modifiers' => 'modifiers',
        'codes' => 'codes',
        'price' => 'price',
        'cost' => 'cost',
        'price_predefined' => 'pricePredefined',
        'position_id' => 'positionId',
        'tax_percent' => 'taxPercent',
        'result_sum' => 'resultSum'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'product' => 'setProduct',
        'modifiers' => 'setModifiers',
        'codes' => 'setCodes',
        'price' => 'setPrice',
        'cost' => 'setCost',
        'price_predefined' => 'setPricePredefined',
        'position_id' => 'setPositionId',
        'tax_percent' => 'setTaxPercent',
        'result_sum' => 'setResultSum'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'product' => 'getProduct',
        'modifiers' => 'getModifiers',
        'codes' => 'getCodes',
        'price' => 'getPrice',
        'cost' => 'getCost',
        'price_predefined' => 'getPricePredefined',
        'position_id' => 'getPositionId',
        'tax_percent' => 'getTaxPercent',
        'result_sum' => 'getResultSum'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }



    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        parent::__construct($data);

        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('modifiers', $data ?? [], null);
        $this->setIfExists('codes', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('cost', $data ?? [], null);
        $this->setIfExists('price_predefined', $data ?? [], null);
        $this->setIfExists('position_id', $data ?? [], null);
        $this->setIfExists('tax_percent', $data ?? [], null);
        $this->setIfExists('result_sum', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['product'] === null) {
            $invalidProperties[] = "'product' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ($this->container['cost'] === null) {
            $invalidProperties[] = "'cost' can't be null";
        }
        if ($this->container['price_predefined'] === null) {
            $invalidProperties[] = "'price_predefined' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets product
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderCancelCause
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderCancelCause $product Item.
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets modifiers
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemModifier[]|null
     */
    public function getModifiers()
    {
        return $this->container['modifiers'];
    }

    /**
     * Sets modifiers
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemModifier[]|null $modifiers Modifiers.
     *
     * @return self
     */
    public function setModifiers($modifiers)
    {
        if (is_null($modifiers)) {
            array_push($this->openAPINullablesSetToNull, 'modifiers');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('modifiers', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['modifiers'] = $modifiers;

        return $this;
    }

    /**
     * Gets codes
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemIdentifierCode[][]|null
     */
    public function getCodes()
    {
        return $this->container['codes'];
    }

    /**
     * Sets codes
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemIdentifierCode[][]|null $codes List of product codes. Each outer list item represents a separate product unit;  each inner list contains codes associated with that unit.   > Allowed from version `9.2.6`.
     *
     * @return self
     */
    public function setCodes($codes)
    {
        if (is_null($codes)) {
            array_push($this->openAPINullablesSetToNull, 'codes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('codes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['codes'] = $codes;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param float $price Price per item unit. Can be sent different from the price in the base menu.
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return float
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param float $cost Total cost per item without tax, discounts/surcharges.
     *
     * @return self
     */
    public function setCost($cost)
    {
        if (is_null($cost)) {
            throw new \InvalidArgumentException('non-nullable cost cannot be null');
        }
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets price_predefined
     *
     * @return bool
     */
    public function getPricePredefined()
    {
        return $this->container['price_predefined'];
    }

    /**
     * Sets price_predefined
     *
     * @param bool $price_predefined Whether price is predefined.
     *
     * @return self
     */
    public function setPricePredefined($price_predefined)
    {
        if (is_null($price_predefined)) {
            throw new \InvalidArgumentException('non-nullable price_predefined cannot be null');
        }
        $this->container['price_predefined'] = $price_predefined;

        return $this;
    }

    /**
     * Gets position_id
     *
     * @return string|null
     */
    public function getPositionId()
    {
        return $this->container['position_id'];
    }

    /**
     * Sets position_id
     *
     * @param string|null $position_id Unique identifier of the item in the order and for the whole system.
     *
     * @return self
     */
    public function setPositionId($position_id)
    {
        if (is_null($position_id)) {
            array_push($this->openAPINullablesSetToNull, 'position_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('position_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['position_id'] = $position_id;

        return $this;
    }

    /**
     * Gets tax_percent
     *
     * @return float|null
     */
    public function getTaxPercent()
    {
        return $this->container['tax_percent'];
    }

    /**
     * Sets tax_percent
     *
     * @param float|null $tax_percent Tax rate.
     *
     * @return self
     */
    public function setTaxPercent($tax_percent)
    {
        if (is_null($tax_percent)) {
            array_push($this->openAPINullablesSetToNull, 'tax_percent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tax_percent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tax_percent'] = $tax_percent;

        return $this;
    }

    /**
     * Gets result_sum
     *
     * @return float|null
     */
    public function getResultSum()
    {
        return $this->container['result_sum'];
    }

    /**
     * Sets result_sum
     *
     * @param float|null $result_sum Total amount per item including tax, discounts/surcharges.
     *
     * @return self
     */
    public function setResultSum($result_sum)
    {
        if (is_null($result_sum)) {
            throw new \InvalidArgumentException('non-nullable result_sum cannot be null');
        }
        $this->container['result_sum'] = $result_sum;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


