<?php
/**
 * IikoNetServiceContractsApiIikoTransportCustomerGetCustomerInfoResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * IikoNetServiceContractsApiIikoTransportCustomerGetCustomerInfoResponse Class Doc Comment
 *
 * @category Class
 * @description Get customer info response.
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IikoNetServiceContractsApiIikoTransportCustomerGetCustomerInfoResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'iikoNet.Service.Contracts.Api.iikoTransport.Customer.GetCustomerInfoResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'referrer_id' => 'string',
        'name' => 'string',
        'surname' => 'string',
        'middle_name' => 'string',
        'comment' => 'string',
        'phone' => 'string',
        'culture_name' => 'string',
        'birthday' => 'string',
        'email' => 'string',
        'sex' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex',
        'consent_status' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex',
        'anonymized' => 'bool',
        'cards' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestCardInfo[]',
        'categories' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestCategoryShortInfo[]',
        'wallet_balances' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestBalanceInfo[]',
        'user_data' => 'string',
        'should_receive_promo_actions_info' => 'bool',
        'should_receive_loyalty_info' => 'bool',
        'should_receive_order_status_info' => 'bool',
        'personal_data_consent_from' => 'string',
        'personal_data_consent_to' => 'string',
        'personal_data_processing_from' => 'string',
        'personal_data_processing_to' => 'string',
        'is_deleted' => 'bool',
        'when_registered' => 'string',
        'last_processed_order_date' => 'string',
        'first_order_date' => 'string',
        'last_visited_organization_id' => 'string',
        'registration_organization_id' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'referrer_id' => 'uuid',
        'name' => null,
        'surname' => null,
        'middle_name' => null,
        'comment' => null,
        'phone' => null,
        'culture_name' => null,
        'birthday' => 'yyyy-MM-dd HH:mm:ss.fff',
        'email' => null,
        'sex' => null,
        'consent_status' => null,
        'anonymized' => null,
        'cards' => null,
        'categories' => null,
        'wallet_balances' => null,
        'user_data' => null,
        'should_receive_promo_actions_info' => null,
        'should_receive_loyalty_info' => null,
        'should_receive_order_status_info' => null,
        'personal_data_consent_from' => 'yyyy-MM-dd HH:mm:ss.fff',
        'personal_data_consent_to' => 'yyyy-MM-dd HH:mm:ss.fff',
        'personal_data_processing_from' => 'yyyy-MM-dd HH:mm:ss.fff',
        'personal_data_processing_to' => 'yyyy-MM-dd HH:mm:ss.fff',
        'is_deleted' => null,
        'when_registered' => 'yyyy-MM-dd HH:mm:ss.fff',
        'last_processed_order_date' => 'yyyy-MM-dd HH:mm:ss.fff',
        'first_order_date' => 'yyyy-MM-dd HH:mm:ss.fff',
        'last_visited_organization_id' => 'uuid',
        'registration_organization_id' => 'uuid'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'referrer_id' => true,
        'name' => false,
        'surname' => false,
        'middle_name' => false,
        'comment' => false,
        'phone' => false,
        'culture_name' => false,
        'birthday' => true,
        'email' => false,
        'sex' => false,
        'consent_status' => false,
        'anonymized' => false,
        'cards' => false,
        'categories' => false,
        'wallet_balances' => false,
        'user_data' => false,
        'should_receive_promo_actions_info' => true,
        'should_receive_loyalty_info' => true,
        'should_receive_order_status_info' => true,
        'personal_data_consent_from' => true,
        'personal_data_consent_to' => true,
        'personal_data_processing_from' => true,
        'personal_data_processing_to' => true,
        'is_deleted' => true,
        'when_registered' => false,
        'last_processed_order_date' => true,
        'first_order_date' => true,
        'last_visited_organization_id' => true,
        'registration_organization_id' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'referrer_id' => 'referrerId',
        'name' => 'name',
        'surname' => 'surname',
        'middle_name' => 'middleName',
        'comment' => 'comment',
        'phone' => 'phone',
        'culture_name' => 'cultureName',
        'birthday' => 'birthday',
        'email' => 'email',
        'sex' => 'sex',
        'consent_status' => 'consentStatus',
        'anonymized' => 'anonymized',
        'cards' => 'cards',
        'categories' => 'categories',
        'wallet_balances' => 'walletBalances',
        'user_data' => 'userData',
        'should_receive_promo_actions_info' => 'shouldReceivePromoActionsInfo',
        'should_receive_loyalty_info' => 'shouldReceiveLoyaltyInfo',
        'should_receive_order_status_info' => 'shouldReceiveOrderStatusInfo',
        'personal_data_consent_from' => 'personalDataConsentFrom',
        'personal_data_consent_to' => 'personalDataConsentTo',
        'personal_data_processing_from' => 'personalDataProcessingFrom',
        'personal_data_processing_to' => 'personalDataProcessingTo',
        'is_deleted' => 'isDeleted',
        'when_registered' => 'whenRegistered',
        'last_processed_order_date' => 'lastProcessedOrderDate',
        'first_order_date' => 'firstOrderDate',
        'last_visited_organization_id' => 'lastVisitedOrganizationId',
        'registration_organization_id' => 'registrationOrganizationId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'referrer_id' => 'setReferrerId',
        'name' => 'setName',
        'surname' => 'setSurname',
        'middle_name' => 'setMiddleName',
        'comment' => 'setComment',
        'phone' => 'setPhone',
        'culture_name' => 'setCultureName',
        'birthday' => 'setBirthday',
        'email' => 'setEmail',
        'sex' => 'setSex',
        'consent_status' => 'setConsentStatus',
        'anonymized' => 'setAnonymized',
        'cards' => 'setCards',
        'categories' => 'setCategories',
        'wallet_balances' => 'setWalletBalances',
        'user_data' => 'setUserData',
        'should_receive_promo_actions_info' => 'setShouldReceivePromoActionsInfo',
        'should_receive_loyalty_info' => 'setShouldReceiveLoyaltyInfo',
        'should_receive_order_status_info' => 'setShouldReceiveOrderStatusInfo',
        'personal_data_consent_from' => 'setPersonalDataConsentFrom',
        'personal_data_consent_to' => 'setPersonalDataConsentTo',
        'personal_data_processing_from' => 'setPersonalDataProcessingFrom',
        'personal_data_processing_to' => 'setPersonalDataProcessingTo',
        'is_deleted' => 'setIsDeleted',
        'when_registered' => 'setWhenRegistered',
        'last_processed_order_date' => 'setLastProcessedOrderDate',
        'first_order_date' => 'setFirstOrderDate',
        'last_visited_organization_id' => 'setLastVisitedOrganizationId',
        'registration_organization_id' => 'setRegistrationOrganizationId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'referrer_id' => 'getReferrerId',
        'name' => 'getName',
        'surname' => 'getSurname',
        'middle_name' => 'getMiddleName',
        'comment' => 'getComment',
        'phone' => 'getPhone',
        'culture_name' => 'getCultureName',
        'birthday' => 'getBirthday',
        'email' => 'getEmail',
        'sex' => 'getSex',
        'consent_status' => 'getConsentStatus',
        'anonymized' => 'getAnonymized',
        'cards' => 'getCards',
        'categories' => 'getCategories',
        'wallet_balances' => 'getWalletBalances',
        'user_data' => 'getUserData',
        'should_receive_promo_actions_info' => 'getShouldReceivePromoActionsInfo',
        'should_receive_loyalty_info' => 'getShouldReceiveLoyaltyInfo',
        'should_receive_order_status_info' => 'getShouldReceiveOrderStatusInfo',
        'personal_data_consent_from' => 'getPersonalDataConsentFrom',
        'personal_data_consent_to' => 'getPersonalDataConsentTo',
        'personal_data_processing_from' => 'getPersonalDataProcessingFrom',
        'personal_data_processing_to' => 'getPersonalDataProcessingTo',
        'is_deleted' => 'getIsDeleted',
        'when_registered' => 'getWhenRegistered',
        'last_processed_order_date' => 'getLastProcessedOrderDate',
        'first_order_date' => 'getFirstOrderDate',
        'last_visited_organization_id' => 'getLastVisitedOrganizationId',
        'registration_organization_id' => 'getRegistrationOrganizationId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('referrer_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('surname', $data ?? [], null);
        $this->setIfExists('middle_name', $data ?? [], null);
        $this->setIfExists('comment', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('culture_name', $data ?? [], null);
        $this->setIfExists('birthday', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('sex', $data ?? [], null);
        $this->setIfExists('consent_status', $data ?? [], null);
        $this->setIfExists('anonymized', $data ?? [], null);
        $this->setIfExists('cards', $data ?? [], null);
        $this->setIfExists('categories', $data ?? [], null);
        $this->setIfExists('wallet_balances', $data ?? [], null);
        $this->setIfExists('user_data', $data ?? [], null);
        $this->setIfExists('should_receive_promo_actions_info', $data ?? [], null);
        $this->setIfExists('should_receive_loyalty_info', $data ?? [], null);
        $this->setIfExists('should_receive_order_status_info', $data ?? [], null);
        $this->setIfExists('personal_data_consent_from', $data ?? [], null);
        $this->setIfExists('personal_data_consent_to', $data ?? [], null);
        $this->setIfExists('personal_data_processing_from', $data ?? [], null);
        $this->setIfExists('personal_data_processing_to', $data ?? [], null);
        $this->setIfExists('is_deleted', $data ?? [], null);
        $this->setIfExists('when_registered', $data ?? [], null);
        $this->setIfExists('last_processed_order_date', $data ?? [], null);
        $this->setIfExists('first_order_date', $data ?? [], null);
        $this->setIfExists('last_visited_organization_id', $data ?? [], null);
        $this->setIfExists('registration_organization_id', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Guest id.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets referrer_id
     *
     * @return string|null
     */
    public function getReferrerId()
    {
        return $this->container['referrer_id'];
    }

    /**
     * Sets referrer_id
     *
     * @param string|null $referrer_id Guest referrer id.
     *
     * @return self
     */
    public function setReferrerId($referrer_id)
    {
        if (is_null($referrer_id)) {
            array_push($this->openAPINullablesSetToNull, 'referrer_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('referrer_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['referrer_id'] = $referrer_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Guest name. Can be null.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets surname
     *
     * @return string|null
     */
    public function getSurname()
    {
        return $this->container['surname'];
    }

    /**
     * Sets surname
     *
     * @param string|null $surname Guest surname. Can be null.
     *
     * @return self
     */
    public function setSurname($surname)
    {
        if (is_null($surname)) {
            throw new \InvalidArgumentException('non-nullable surname cannot be null');
        }
        $this->container['surname'] = $surname;

        return $this;
    }

    /**
     * Gets middle_name
     *
     * @return string|null
     */
    public function getMiddleName()
    {
        return $this->container['middle_name'];
    }

    /**
     * Sets middle_name
     *
     * @param string|null $middle_name Guest middle name. Can be null.
     *
     * @return self
     */
    public function setMiddleName($middle_name)
    {
        if (is_null($middle_name)) {
            throw new \InvalidArgumentException('non-nullable middle_name cannot be null');
        }
        $this->container['middle_name'] = $middle_name;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment Guest comment. Can be null.
     *
     * @return self
     */
    public function setComment($comment)
    {
        if (is_null($comment)) {
            throw new \InvalidArgumentException('non-nullable comment cannot be null');
        }
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Main customer's phone. Can be null.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets culture_name
     *
     * @return string|null
     */
    public function getCultureName()
    {
        return $this->container['culture_name'];
    }

    /**
     * Sets culture_name
     *
     * @param string|null $culture_name Guest culture name. Can be null.
     *
     * @return self
     */
    public function setCultureName($culture_name)
    {
        if (is_null($culture_name)) {
            throw new \InvalidArgumentException('non-nullable culture_name cannot be null');
        }
        $this->container['culture_name'] = $culture_name;

        return $this;
    }

    /**
     * Gets birthday
     *
     * @return string|null
     */
    public function getBirthday()
    {
        return $this->container['birthday'];
    }

    /**
     * Sets birthday
     *
     * @param string|null $birthday Guest birthday.
     *
     * @return self
     */
    public function setBirthday($birthday)
    {
        if (is_null($birthday)) {
            array_push($this->openAPINullablesSetToNull, 'birthday');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birthday', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birthday'] = $birthday;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Guest email. Can be null.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets sex
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex|null
     */
    public function getSex()
    {
        return $this->container['sex'];
    }

    /**
     * Sets sex
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex|null $sex Sex.  <br>0 - not specified,<br />1 - male,<br />2 - female.
     *
     * @return self
     */
    public function setSex($sex)
    {
        if (is_null($sex)) {
            throw new \InvalidArgumentException('non-nullable sex cannot be null');
        }
        $this->container['sex'] = $sex;

        return $this;
    }

    /**
     * Gets consent_status
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex|null
     */
    public function getConsentStatus()
    {
        return $this->container['consent_status'];
    }

    /**
     * Sets consent_status
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex|null $consent_status Guest consent status.  <br>0 - unknown,<br />1 - given,<br />2 - revoked.
     *
     * @return self
     */
    public function setConsentStatus($consent_status)
    {
        if (is_null($consent_status)) {
            throw new \InvalidArgumentException('non-nullable consent_status cannot be null');
        }
        $this->container['consent_status'] = $consent_status;

        return $this;
    }

    /**
     * Gets anonymized
     *
     * @return bool|null
     */
    public function getAnonymized()
    {
        return $this->container['anonymized'];
    }

    /**
     * Sets anonymized
     *
     * @param bool|null $anonymized Guest anonymized.
     *
     * @return self
     */
    public function setAnonymized($anonymized)
    {
        if (is_null($anonymized)) {
            throw new \InvalidArgumentException('non-nullable anonymized cannot be null');
        }
        $this->container['anonymized'] = $anonymized;

        return $this;
    }

    /**
     * Gets cards
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestCardInfo[]|null
     */
    public function getCards()
    {
        return $this->container['cards'];
    }

    /**
     * Sets cards
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestCardInfo[]|null $cards Customer's cards.
     *
     * @return self
     */
    public function setCards($cards)
    {
        if (is_null($cards)) {
            throw new \InvalidArgumentException('non-nullable cards cannot be null');
        }
        $this->container['cards'] = $cards;

        return $this;
    }

    /**
     * Gets categories
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestCategoryShortInfo[]|null
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestCategoryShortInfo[]|null $categories Customer categories.
     *
     * @return self
     */
    public function setCategories($categories)
    {
        if (is_null($categories)) {
            throw new \InvalidArgumentException('non-nullable categories cannot be null');
        }
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets wallet_balances
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestBalanceInfo[]|null
     */
    public function getWalletBalances()
    {
        return $this->container['wallet_balances'];
    }

    /**
     * Sets wallet_balances
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerGuestBalanceInfo[]|null $wallet_balances Customer's user wallets. Contains bonus balances of different loyalty programs.
     *
     * @return self
     */
    public function setWalletBalances($wallet_balances)
    {
        if (is_null($wallet_balances)) {
            throw new \InvalidArgumentException('non-nullable wallet_balances cannot be null');
        }
        $this->container['wallet_balances'] = $wallet_balances;

        return $this;
    }

    /**
     * Gets user_data
     *
     * @return string|null
     */
    public function getUserData()
    {
        return $this->container['user_data'];
    }

    /**
     * Sets user_data
     *
     * @param string|null $user_data Technical user data, customizable by restaurateur. Can be null.
     *
     * @return self
     */
    public function setUserData($user_data)
    {
        if (is_null($user_data)) {
            throw new \InvalidArgumentException('non-nullable user_data cannot be null');
        }
        $this->container['user_data'] = $user_data;

        return $this;
    }

    /**
     * Gets should_receive_promo_actions_info
     *
     * @return bool|null
     */
    public function getShouldReceivePromoActionsInfo()
    {
        return $this->container['should_receive_promo_actions_info'];
    }

    /**
     * Sets should_receive_promo_actions_info
     *
     * @param bool|null $should_receive_promo_actions_info Customer get promo messages (email, sms). If null - unknown.
     *
     * @return self
     */
    public function setShouldReceivePromoActionsInfo($should_receive_promo_actions_info)
    {
        if (is_null($should_receive_promo_actions_info)) {
            array_push($this->openAPINullablesSetToNull, 'should_receive_promo_actions_info');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('should_receive_promo_actions_info', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['should_receive_promo_actions_info'] = $should_receive_promo_actions_info;

        return $this;
    }

    /**
     * Gets should_receive_loyalty_info
     *
     * @return bool|null
     */
    public function getShouldReceiveLoyaltyInfo()
    {
        return $this->container['should_receive_loyalty_info'];
    }

    /**
     * Sets should_receive_loyalty_info
     *
     * @param bool|null $should_receive_loyalty_info Guest should receive loyalty info.
     *
     * @return self
     */
    public function setShouldReceiveLoyaltyInfo($should_receive_loyalty_info)
    {
        if (is_null($should_receive_loyalty_info)) {
            array_push($this->openAPINullablesSetToNull, 'should_receive_loyalty_info');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('should_receive_loyalty_info', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['should_receive_loyalty_info'] = $should_receive_loyalty_info;

        return $this;
    }

    /**
     * Gets should_receive_order_status_info
     *
     * @return bool|null
     */
    public function getShouldReceiveOrderStatusInfo()
    {
        return $this->container['should_receive_order_status_info'];
    }

    /**
     * Sets should_receive_order_status_info
     *
     * @param bool|null $should_receive_order_status_info Guest should receive order status info.
     *
     * @return self
     */
    public function setShouldReceiveOrderStatusInfo($should_receive_order_status_info)
    {
        if (is_null($should_receive_order_status_info)) {
            array_push($this->openAPINullablesSetToNull, 'should_receive_order_status_info');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('should_receive_order_status_info', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['should_receive_order_status_info'] = $should_receive_order_status_info;

        return $this;
    }

    /**
     * Gets personal_data_consent_from
     *
     * @return string|null
     */
    public function getPersonalDataConsentFrom()
    {
        return $this->container['personal_data_consent_from'];
    }

    /**
     * Sets personal_data_consent_from
     *
     * @param string|null $personal_data_consent_from Guest personal data consent from.
     *
     * @return self
     */
    public function setPersonalDataConsentFrom($personal_data_consent_from)
    {
        if (is_null($personal_data_consent_from)) {
            array_push($this->openAPINullablesSetToNull, 'personal_data_consent_from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('personal_data_consent_from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['personal_data_consent_from'] = $personal_data_consent_from;

        return $this;
    }

    /**
     * Gets personal_data_consent_to
     *
     * @return string|null
     */
    public function getPersonalDataConsentTo()
    {
        return $this->container['personal_data_consent_to'];
    }

    /**
     * Sets personal_data_consent_to
     *
     * @param string|null $personal_data_consent_to Guest personal data consent to.
     *
     * @return self
     */
    public function setPersonalDataConsentTo($personal_data_consent_to)
    {
        if (is_null($personal_data_consent_to)) {
            array_push($this->openAPINullablesSetToNull, 'personal_data_consent_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('personal_data_consent_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['personal_data_consent_to'] = $personal_data_consent_to;

        return $this;
    }

    /**
     * Gets personal_data_processing_from
     *
     * @return string|null
     */
    public function getPersonalDataProcessingFrom()
    {
        return $this->container['personal_data_processing_from'];
    }

    /**
     * Sets personal_data_processing_from
     *
     * @param string|null $personal_data_processing_from Guest personal data processing from.
     *
     * @return self
     */
    public function setPersonalDataProcessingFrom($personal_data_processing_from)
    {
        if (is_null($personal_data_processing_from)) {
            array_push($this->openAPINullablesSetToNull, 'personal_data_processing_from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('personal_data_processing_from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['personal_data_processing_from'] = $personal_data_processing_from;

        return $this;
    }

    /**
     * Gets personal_data_processing_to
     *
     * @return string|null
     */
    public function getPersonalDataProcessingTo()
    {
        return $this->container['personal_data_processing_to'];
    }

    /**
     * Sets personal_data_processing_to
     *
     * @param string|null $personal_data_processing_to Guest personal data processing to.
     *
     * @return self
     */
    public function setPersonalDataProcessingTo($personal_data_processing_to)
    {
        if (is_null($personal_data_processing_to)) {
            array_push($this->openAPINullablesSetToNull, 'personal_data_processing_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('personal_data_processing_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['personal_data_processing_to'] = $personal_data_processing_to;

        return $this;
    }

    /**
     * Gets is_deleted
     *
     * @return bool|null
     */
    public function getIsDeleted()
    {
        return $this->container['is_deleted'];
    }

    /**
     * Sets is_deleted
     *
     * @param bool|null $is_deleted Customer marked as deleted.
     *
     * @return self
     */
    public function setIsDeleted($is_deleted)
    {
        if (is_null($is_deleted)) {
            array_push($this->openAPINullablesSetToNull, 'is_deleted');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_deleted', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_deleted'] = $is_deleted;

        return $this;
    }

    /**
     * Gets when_registered
     *
     * @return string|null
     */
    public function getWhenRegistered()
    {
        return $this->container['when_registered'];
    }

    /**
     * Sets when_registered
     *
     * @param string|null $when_registered Registration date.
     *
     * @return self
     */
    public function setWhenRegistered($when_registered)
    {
        if (is_null($when_registered)) {
            throw new \InvalidArgumentException('non-nullable when_registered cannot be null');
        }
        $this->container['when_registered'] = $when_registered;

        return $this;
    }

    /**
     * Gets last_processed_order_date
     *
     * @return string|null
     */
    public function getLastProcessedOrderDate()
    {
        return $this->container['last_processed_order_date'];
    }

    /**
     * Sets last_processed_order_date
     *
     * @param string|null $last_processed_order_date Last order date.
     *
     * @return self
     */
    public function setLastProcessedOrderDate($last_processed_order_date)
    {
        if (is_null($last_processed_order_date)) {
            array_push($this->openAPINullablesSetToNull, 'last_processed_order_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_processed_order_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_processed_order_date'] = $last_processed_order_date;

        return $this;
    }

    /**
     * Gets first_order_date
     *
     * @return string|null
     */
    public function getFirstOrderDate()
    {
        return $this->container['first_order_date'];
    }

    /**
     * Sets first_order_date
     *
     * @param string|null $first_order_date First order date.
     *
     * @return self
     */
    public function setFirstOrderDate($first_order_date)
    {
        if (is_null($first_order_date)) {
            array_push($this->openAPINullablesSetToNull, 'first_order_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('first_order_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['first_order_date'] = $first_order_date;

        return $this;
    }

    /**
     * Gets last_visited_organization_id
     *
     * @return string|null
     */
    public function getLastVisitedOrganizationId()
    {
        return $this->container['last_visited_organization_id'];
    }

    /**
     * Sets last_visited_organization_id
     *
     * @param string|null $last_visited_organization_id Guest last visited organization id.
     *
     * @return self
     */
    public function setLastVisitedOrganizationId($last_visited_organization_id)
    {
        if (is_null($last_visited_organization_id)) {
            array_push($this->openAPINullablesSetToNull, 'last_visited_organization_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_visited_organization_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_visited_organization_id'] = $last_visited_organization_id;

        return $this;
    }

    /**
     * Gets registration_organization_id
     *
     * @return string|null
     */
    public function getRegistrationOrganizationId()
    {
        return $this->container['registration_organization_id'];
    }

    /**
     * Sets registration_organization_id
     *
     * @param string|null $registration_organization_id Guest registration organization id.
     *
     * @return self
     */
    public function setRegistrationOrganizationId($registration_organization_id)
    {
        if (is_null($registration_organization_id)) {
            array_push($this->openAPINullablesSetToNull, 'registration_organization_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('registration_organization_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['registration_organization_id'] = $registration_organization_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


