<?php
/**
 * ExternalMenuItemSize
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * ExternalMenuItemSize Class Doc Comment
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExternalMenuItemSize implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ExternalMenuItemSize';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'sku' => 'string',
        'size_code' => 'string',
        'size_name' => 'string',
        'is_default' => 'bool',
        'portion_weight_grams' => 'float',
        'item_modifier_groups' => '\IIKO\Model\ExternalMenuModifierGroup[]',
        'size_id' => 'string',
        'nutrition_per_hundred_grams' => '\IIKO\Model\NutritionInfoDto[]',
        'prices' => '\IIKO\Model\ExternalMenuPriceByDepartmentsDto[]',
        'nutritions' => '\IIKO\Model\NutritionInfoDto[]',
        'is_hidden' => 'bool',
        'measure_unit_type' => 'string',
        'button_image_url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'sku' => null,
        'size_code' => null,
        'size_name' => null,
        'is_default' => null,
        'portion_weight_grams' => null,
        'item_modifier_groups' => null,
        'size_id' => null,
        'nutrition_per_hundred_grams' => null,
        'prices' => null,
        'nutritions' => null,
        'is_hidden' => null,
        'measure_unit_type' => null,
        'button_image_url' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'sku' => false,
        'size_code' => true,
        'size_name' => true,
        'is_default' => false,
        'portion_weight_grams' => false,
        'item_modifier_groups' => false,
        'size_id' => false,
        'nutrition_per_hundred_grams' => false,
        'prices' => false,
        'nutritions' => false,
        'is_hidden' => false,
        'measure_unit_type' => false,
        'button_image_url' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sku' => 'sku',
        'size_code' => 'sizeCode',
        'size_name' => 'sizeName',
        'is_default' => 'isDefault',
        'portion_weight_grams' => 'portionWeightGrams',
        'item_modifier_groups' => 'itemModifierGroups',
        'size_id' => 'sizeId',
        'nutrition_per_hundred_grams' => 'nutritionPerHundredGrams',
        'prices' => 'prices',
        'nutritions' => 'nutritions',
        'is_hidden' => 'isHidden',
        'measure_unit_type' => 'measureUnitType',
        'button_image_url' => 'buttonImageUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sku' => 'setSku',
        'size_code' => 'setSizeCode',
        'size_name' => 'setSizeName',
        'is_default' => 'setIsDefault',
        'portion_weight_grams' => 'setPortionWeightGrams',
        'item_modifier_groups' => 'setItemModifierGroups',
        'size_id' => 'setSizeId',
        'nutrition_per_hundred_grams' => 'setNutritionPerHundredGrams',
        'prices' => 'setPrices',
        'nutritions' => 'setNutritions',
        'is_hidden' => 'setIsHidden',
        'measure_unit_type' => 'setMeasureUnitType',
        'button_image_url' => 'setButtonImageUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sku' => 'getSku',
        'size_code' => 'getSizeCode',
        'size_name' => 'getSizeName',
        'is_default' => 'getIsDefault',
        'portion_weight_grams' => 'getPortionWeightGrams',
        'item_modifier_groups' => 'getItemModifierGroups',
        'size_id' => 'getSizeId',
        'nutrition_per_hundred_grams' => 'getNutritionPerHundredGrams',
        'prices' => 'getPrices',
        'nutritions' => 'getNutritions',
        'is_hidden' => 'getIsHidden',
        'measure_unit_type' => 'getMeasureUnitType',
        'button_image_url' => 'getButtonImageUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('sku', $data ?? [], '');
        $this->setIfExists('size_code', $data ?? [], null);
        $this->setIfExists('size_name', $data ?? [], null);
        $this->setIfExists('is_default', $data ?? [], false);
        $this->setIfExists('portion_weight_grams', $data ?? [], null);
        $this->setIfExists('item_modifier_groups', $data ?? [], null);
        $this->setIfExists('size_id', $data ?? [], null);
        $this->setIfExists('nutrition_per_hundred_grams', $data ?? [], null);
        $this->setIfExists('prices', $data ?? [], null);
        $this->setIfExists('nutritions', $data ?? [], null);
        $this->setIfExists('is_hidden', $data ?? [], false);
        $this->setIfExists('measure_unit_type', $data ?? [], 'GRAM');
        $this->setIfExists('button_image_url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['item_modifier_groups'] === null) {
            $invalidProperties[] = "'item_modifier_groups' can't be null";
        }
        if ($this->container['size_id'] === null) {
            $invalidProperties[] = "'size_id' can't be null";
        }
        if ($this->container['nutrition_per_hundred_grams'] === null) {
            $invalidProperties[] = "'nutrition_per_hundred_grams' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sku
     *
     * @return string|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku Unique size code, consists of the product code and the name of the size, if the product has one size, then the size code will be equal to the product code
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets size_code
     *
     * @return string|null
     */
    public function getSizeCode()
    {
        return $this->container['size_code'];
    }

    /**
     * Sets size_code
     *
     * @param string|null $size_code size_code
     *
     * @return self
     */
    public function setSizeCode($size_code)
    {
        if (is_null($size_code)) {
            array_push($this->openAPINullablesSetToNull, 'size_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('size_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['size_code'] = $size_code;

        return $this;
    }

    /**
     * Gets size_name
     *
     * @return string|null
     */
    public function getSizeName()
    {
        return $this->container['size_name'];
    }

    /**
     * Sets size_name
     *
     * @param string|null $size_name Name of the product size, the name can be empty if there is only one size in the list
     *
     * @return self
     */
    public function setSizeName($size_name)
    {
        if (is_null($size_name)) {
            array_push($this->openAPINullablesSetToNull, 'size_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('size_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['size_name'] = $size_name;

        return $this;
    }

    /**
     * Gets is_default
     *
     * @return bool|null
     */
    public function getIsDefault()
    {
        return $this->container['is_default'];
    }

    /**
     * Sets is_default
     *
     * @param bool|null $is_default Whether it is a default size of the product. If the product has one size, then the parameter will be true, if the product has several sizes, none of them can be default.
     *
     * @return self
     */
    public function setIsDefault($is_default)
    {
        if (is_null($is_default)) {
            throw new \InvalidArgumentException('non-nullable is_default cannot be null');
        }
        $this->container['is_default'] = $is_default;

        return $this;
    }

    /**
     * Gets portion_weight_grams
     *
     * @return float|null
     */
    public function getPortionWeightGrams()
    {
        return $this->container['portion_weight_grams'];
    }

    /**
     * Sets portion_weight_grams
     *
     * @param float|null $portion_weight_grams Size's weight
     *
     * @return self
     */
    public function setPortionWeightGrams($portion_weight_grams)
    {
        if (is_null($portion_weight_grams)) {
            throw new \InvalidArgumentException('non-nullable portion_weight_grams cannot be null');
        }
        $this->container['portion_weight_grams'] = $portion_weight_grams;

        return $this;
    }

    /**
     * Gets item_modifier_groups
     *
     * @return \IIKO\Model\ExternalMenuModifierGroup[]
     */
    public function getItemModifierGroups()
    {
        return $this->container['item_modifier_groups'];
    }

    /**
     * Sets item_modifier_groups
     *
     * @param \IIKO\Model\ExternalMenuModifierGroup[] $item_modifier_groups item_modifier_groups
     *
     * @return self
     */
    public function setItemModifierGroups($item_modifier_groups)
    {
        if (is_null($item_modifier_groups)) {
            throw new \InvalidArgumentException('non-nullable item_modifier_groups cannot be null');
        }
        $this->container['item_modifier_groups'] = $item_modifier_groups;

        return $this;
    }

    /**
     * Gets size_id
     *
     * @return string
     */
    public function getSizeId()
    {
        return $this->container['size_id'];
    }

    /**
     * Sets size_id
     *
     * @param string $size_id ID size, can be empty if the default size is selected and it is the only size in the list
     *
     * @return self
     */
    public function setSizeId($size_id)
    {
        if (is_null($size_id)) {
            throw new \InvalidArgumentException('non-nullable size_id cannot be null');
        }
        $this->container['size_id'] = $size_id;

        return $this;
    }

    /**
     * Gets nutrition_per_hundred_grams
     *
     * @return \IIKO\Model\NutritionInfoDto[]
     */
    public function getNutritionPerHundredGrams()
    {
        return $this->container['nutrition_per_hundred_grams'];
    }

    /**
     * Sets nutrition_per_hundred_grams
     *
     * @param \IIKO\Model\NutritionInfoDto[] $nutrition_per_hundred_grams Nutrition per 100 g of product
     *
     * @return self
     */
    public function setNutritionPerHundredGrams($nutrition_per_hundred_grams)
    {
        if (is_null($nutrition_per_hundred_grams)) {
            throw new \InvalidArgumentException('non-nullable nutrition_per_hundred_grams cannot be null');
        }
        $this->container['nutrition_per_hundred_grams'] = $nutrition_per_hundred_grams;

        return $this;
    }

    /**
     * Gets prices
     *
     * @return \IIKO\Model\ExternalMenuPriceByDepartmentsDto[]|null
     */
    public function getPrices()
    {
        return $this->container['prices'];
    }

    /**
     * Sets prices
     *
     * @param \IIKO\Model\ExternalMenuPriceByDepartmentsDto[]|null $prices prices
     *
     * @return self
     */
    public function setPrices($prices)
    {
        if (is_null($prices)) {
            throw new \InvalidArgumentException('non-nullable prices cannot be null');
        }
        $this->container['prices'] = $prices;

        return $this;
    }

    /**
     * Gets nutritions
     *
     * @return \IIKO\Model\NutritionInfoDto[]|null
     */
    public function getNutritions()
    {
        return $this->container['nutritions'];
    }

    /**
     * Sets nutritions
     *
     * @param \IIKO\Model\NutritionInfoDto[]|null $nutritions Nutrition per 100 g of product grouped by departments
     *
     * @return self
     */
    public function setNutritions($nutritions)
    {
        if (is_null($nutritions)) {
            throw new \InvalidArgumentException('non-nullable nutritions cannot be null');
        }
        $this->container['nutritions'] = $nutritions;

        return $this;
    }

    /**
     * Gets is_hidden
     *
     * @return bool|null
     */
    public function getIsHidden()
    {
        return $this->container['is_hidden'];
    }

    /**
     * Sets is_hidden
     *
     * @param bool|null $is_hidden is_hidden
     *
     * @return self
     */
    public function setIsHidden($is_hidden)
    {
        if (is_null($is_hidden)) {
            throw new \InvalidArgumentException('non-nullable is_hidden cannot be null');
        }
        $this->container['is_hidden'] = $is_hidden;

        return $this;
    }

    /**
     * Gets measure_unit_type
     *
     * @return string|null
     */
    public function getMeasureUnitType()
    {
        return $this->container['measure_unit_type'];
    }

    /**
     * Sets measure_unit_type
     *
     * @param string|null $measure_unit_type measure_unit_type
     *
     * @return self
     */
    public function setMeasureUnitType($measure_unit_type)
    {
        if (is_null($measure_unit_type)) {
            throw new \InvalidArgumentException('non-nullable measure_unit_type cannot be null');
        }
        $this->container['measure_unit_type'] = $measure_unit_type;

        return $this;
    }

    /**
     * Gets button_image_url
     *
     * @return string|null
     */
    public function getButtonImageUrl()
    {
        return $this->container['button_image_url'];
    }

    /**
     * Sets button_image_url
     *
     * @param string|null $button_image_url links to images
     *
     * @return self
     */
    public function setButtonImageUrl($button_image_url)
    {
        if (is_null($button_image_url)) {
            array_push($this->openAPINullablesSetToNull, 'button_image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('button_image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['button_image_url'] = $button_image_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


