<?php
/**
 * IikoNetServiceContractsApiIikoTransportLoyaltyResultCalculateCheckinResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * IikoNetServiceContractsApiIikoTransportLoyaltyResultCalculateCheckinResponse Class Doc Comment
 *
 * @category Class
 * @description Loyalty result for order.
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IikoNetServiceContractsApiIikoTransportLoyaltyResultCalculateCheckinResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'iikoNet.Service.Contracts.Api.iikoTransport.LoyaltyResult.CalculateCheckinResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'loyalty_program_results' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultLoyaltyProgramResult[]',
        'available_payments' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultAvailablePayment[]',
        'validation_warnings' => 'string[]',
        'warnings' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultWarningInfo[]',
        'loyalty_trace' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'loyalty_program_results' => null,
        'available_payments' => null,
        'validation_warnings' => null,
        'warnings' => null,
        'loyalty_trace' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'loyalty_program_results' => false,
        'available_payments' => false,
        'validation_warnings' => false,
        'warnings' => false,
        'loyalty_trace' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'loyalty_program_results' => 'loyaltyProgramResults',
        'available_payments' => 'availablePayments',
        'validation_warnings' => 'validationWarnings',
        'warnings' => 'Warnings',
        'loyalty_trace' => 'loyaltyTrace'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'loyalty_program_results' => 'setLoyaltyProgramResults',
        'available_payments' => 'setAvailablePayments',
        'validation_warnings' => 'setValidationWarnings',
        'warnings' => 'setWarnings',
        'loyalty_trace' => 'setLoyaltyTrace'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'loyalty_program_results' => 'getLoyaltyProgramResults',
        'available_payments' => 'getAvailablePayments',
        'validation_warnings' => 'getValidationWarnings',
        'warnings' => 'getWarnings',
        'loyalty_trace' => 'getLoyaltyTrace'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('loyalty_program_results', $data ?? [], null);
        $this->setIfExists('available_payments', $data ?? [], null);
        $this->setIfExists('validation_warnings', $data ?? [], null);
        $this->setIfExists('warnings', $data ?? [], null);
        $this->setIfExists('loyalty_trace', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets loyalty_program_results
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultLoyaltyProgramResult[]|null
     */
    public function getLoyaltyProgramResults()
    {
        return $this->container['loyalty_program_results'];
    }

    /**
     * Sets loyalty_program_results
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultLoyaltyProgramResult[]|null $loyalty_program_results Loyalty program results.
     *
     * @return self
     */
    public function setLoyaltyProgramResults($loyalty_program_results)
    {
        if (is_null($loyalty_program_results)) {
            throw new \InvalidArgumentException('non-nullable loyalty_program_results cannot be null');
        }
        $this->container['loyalty_program_results'] = $loyalty_program_results;

        return $this;
    }

    /**
     * Gets available_payments
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultAvailablePayment[]|null
     */
    public function getAvailablePayments()
    {
        return $this->container['available_payments'];
    }

    /**
     * Sets available_payments
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultAvailablePayment[]|null $available_payments Marketing campaigns with available payments.
     *
     * @return self
     */
    public function setAvailablePayments($available_payments)
    {
        if (is_null($available_payments)) {
            throw new \InvalidArgumentException('non-nullable available_payments cannot be null');
        }
        $this->container['available_payments'] = $available_payments;

        return $this;
    }

    /**
     * Gets validation_warnings
     *
     * @return string[]|null
     */
    public function getValidationWarnings()
    {
        return $this->container['validation_warnings'];
    }

    /**
     * Sets validation_warnings
     *
     * @param string[]|null $validation_warnings Warnings about errors, not blocking loyalty calculation.
     *
     * @return self
     */
    public function setValidationWarnings($validation_warnings)
    {
        if (is_null($validation_warnings)) {
            throw new \InvalidArgumentException('non-nullable validation_warnings cannot be null');
        }
        $this->container['validation_warnings'] = $validation_warnings;

        return $this;
    }

    /**
     * Gets warnings
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultWarningInfo[]|null
     */
    public function getWarnings()
    {
        return $this->container['warnings'];
    }

    /**
     * Sets warnings
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportLoyaltyResultWarningInfo[]|null $warnings Warnings about errors, not blocking loyalty calculation.
     *
     * @return self
     */
    public function setWarnings($warnings)
    {
        if (is_null($warnings)) {
            throw new \InvalidArgumentException('non-nullable warnings cannot be null');
        }
        $this->container['warnings'] = $warnings;

        return $this;
    }

    /**
     * Gets loyalty_trace
     *
     * @return string|null
     */
    public function getLoyaltyTrace()
    {
        return $this->container['loyalty_trace'];
    }

    /**
     * Sets loyalty_trace
     *
     * @param string|null $loyalty_trace Loyalty trace. Can be null.
     *
     * @return self
     */
    public function setLoyaltyTrace($loyalty_trace)
    {
        if (is_null($loyalty_trace)) {
            throw new \InvalidArgumentException('non-nullable loyalty_trace cannot be null');
        }
        $this->container['loyalty_trace'] = $loyalty_trace;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


