<?php
/**
 * IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryRestrictions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryRestrictions Class Doc Comment
 *
 * @category Class
 * @description Delivery restrictions.
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryRestrictions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'iikoTransport.PublicApi.Contracts.DeliveryRestrictions.DeliveryRestrictions';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'organization_id' => 'string',
        'delivery_geocode_service_type' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryGeocodeServiceType',
        'delivery_regions_map_url' => 'string',
        'default_delivery_duration_in_minutes' => 'int',
        'default_self_service_duration_in_minutes' => 'int',
        'use_same_delivery_duration' => 'bool',
        'use_same_min_sum' => 'bool',
        'default_min_sum' => 'float',
        'use_same_work_time_interval' => 'bool',
        'default_from' => 'int',
        'default_to' => 'int',
        'use_same_restrictions_on_all_week' => 'bool',
        'restrictions' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryRestrictionItem[]',
        'delivery_zones' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryZone[]',
        'reject_on_geocoding_error' => 'bool',
        'add_delivery_service_cost' => 'bool',
        'use_same_delivery_service_product' => 'bool',
        'default_delivery_service_product_id' => 'string',
        'use_external_assignation_service' => 'bool',
        'front_trusts_call_center_check' => 'bool',
        'external_assignation_service_url' => 'string',
        'require_exact_address_for_geocoding' => 'bool',
        'zones_mode' => '\IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex',
        'auto_assign_external_deliveries' => 'bool',
        'action_on_validation_rejection' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsActionOnValidationRejection'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'organization_id' => 'uuid',
        'delivery_geocode_service_type' => null,
        'delivery_regions_map_url' => null,
        'default_delivery_duration_in_minutes' => 'int64',
        'default_self_service_duration_in_minutes' => 'int64',
        'use_same_delivery_duration' => null,
        'use_same_min_sum' => null,
        'default_min_sum' => 'double',
        'use_same_work_time_interval' => null,
        'default_from' => 'int32',
        'default_to' => 'int32',
        'use_same_restrictions_on_all_week' => null,
        'restrictions' => null,
        'delivery_zones' => null,
        'reject_on_geocoding_error' => null,
        'add_delivery_service_cost' => null,
        'use_same_delivery_service_product' => null,
        'default_delivery_service_product_id' => 'uuid',
        'use_external_assignation_service' => null,
        'front_trusts_call_center_check' => null,
        'external_assignation_service_url' => null,
        'require_exact_address_for_geocoding' => null,
        'zones_mode' => null,
        'auto_assign_external_deliveries' => null,
        'action_on_validation_rejection' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'organization_id' => false,
        'delivery_geocode_service_type' => false,
        'delivery_regions_map_url' => true,
        'default_delivery_duration_in_minutes' => false,
        'default_self_service_duration_in_minutes' => false,
        'use_same_delivery_duration' => false,
        'use_same_min_sum' => false,
        'default_min_sum' => true,
        'use_same_work_time_interval' => false,
        'default_from' => true,
        'default_to' => true,
        'use_same_restrictions_on_all_week' => false,
        'restrictions' => false,
        'delivery_zones' => false,
        'reject_on_geocoding_error' => false,
        'add_delivery_service_cost' => false,
        'use_same_delivery_service_product' => false,
        'default_delivery_service_product_id' => true,
        'use_external_assignation_service' => false,
        'front_trusts_call_center_check' => false,
        'external_assignation_service_url' => true,
        'require_exact_address_for_geocoding' => false,
        'zones_mode' => false,
        'auto_assign_external_deliveries' => false,
        'action_on_validation_rejection' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'organization_id' => 'organizationId',
        'delivery_geocode_service_type' => 'deliveryGeocodeServiceType',
        'delivery_regions_map_url' => 'deliveryRegionsMapUrl',
        'default_delivery_duration_in_minutes' => 'defaultDeliveryDurationInMinutes',
        'default_self_service_duration_in_minutes' => 'defaultSelfServiceDurationInMinutes',
        'use_same_delivery_duration' => 'useSameDeliveryDuration',
        'use_same_min_sum' => 'useSameMinSum',
        'default_min_sum' => 'defaultMinSum',
        'use_same_work_time_interval' => 'useSameWorkTimeInterval',
        'default_from' => 'defaultFrom',
        'default_to' => 'defaultTo',
        'use_same_restrictions_on_all_week' => 'useSameRestrictionsOnAllWeek',
        'restrictions' => 'restrictions',
        'delivery_zones' => 'deliveryZones',
        'reject_on_geocoding_error' => 'rejectOnGeocodingError',
        'add_delivery_service_cost' => 'addDeliveryServiceCost',
        'use_same_delivery_service_product' => 'useSameDeliveryServiceProduct',
        'default_delivery_service_product_id' => 'defaultDeliveryServiceProductId',
        'use_external_assignation_service' => 'useExternalAssignationService',
        'front_trusts_call_center_check' => 'frontTrustsCallCenterCheck',
        'external_assignation_service_url' => 'externalAssignationServiceUrl',
        'require_exact_address_for_geocoding' => 'requireExactAddressForGeocoding',
        'zones_mode' => 'zonesMode',
        'auto_assign_external_deliveries' => 'autoAssignExternalDeliveries',
        'action_on_validation_rejection' => 'actionOnValidationRejection'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'organization_id' => 'setOrganizationId',
        'delivery_geocode_service_type' => 'setDeliveryGeocodeServiceType',
        'delivery_regions_map_url' => 'setDeliveryRegionsMapUrl',
        'default_delivery_duration_in_minutes' => 'setDefaultDeliveryDurationInMinutes',
        'default_self_service_duration_in_minutes' => 'setDefaultSelfServiceDurationInMinutes',
        'use_same_delivery_duration' => 'setUseSameDeliveryDuration',
        'use_same_min_sum' => 'setUseSameMinSum',
        'default_min_sum' => 'setDefaultMinSum',
        'use_same_work_time_interval' => 'setUseSameWorkTimeInterval',
        'default_from' => 'setDefaultFrom',
        'default_to' => 'setDefaultTo',
        'use_same_restrictions_on_all_week' => 'setUseSameRestrictionsOnAllWeek',
        'restrictions' => 'setRestrictions',
        'delivery_zones' => 'setDeliveryZones',
        'reject_on_geocoding_error' => 'setRejectOnGeocodingError',
        'add_delivery_service_cost' => 'setAddDeliveryServiceCost',
        'use_same_delivery_service_product' => 'setUseSameDeliveryServiceProduct',
        'default_delivery_service_product_id' => 'setDefaultDeliveryServiceProductId',
        'use_external_assignation_service' => 'setUseExternalAssignationService',
        'front_trusts_call_center_check' => 'setFrontTrustsCallCenterCheck',
        'external_assignation_service_url' => 'setExternalAssignationServiceUrl',
        'require_exact_address_for_geocoding' => 'setRequireExactAddressForGeocoding',
        'zones_mode' => 'setZonesMode',
        'auto_assign_external_deliveries' => 'setAutoAssignExternalDeliveries',
        'action_on_validation_rejection' => 'setActionOnValidationRejection'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'organization_id' => 'getOrganizationId',
        'delivery_geocode_service_type' => 'getDeliveryGeocodeServiceType',
        'delivery_regions_map_url' => 'getDeliveryRegionsMapUrl',
        'default_delivery_duration_in_minutes' => 'getDefaultDeliveryDurationInMinutes',
        'default_self_service_duration_in_minutes' => 'getDefaultSelfServiceDurationInMinutes',
        'use_same_delivery_duration' => 'getUseSameDeliveryDuration',
        'use_same_min_sum' => 'getUseSameMinSum',
        'default_min_sum' => 'getDefaultMinSum',
        'use_same_work_time_interval' => 'getUseSameWorkTimeInterval',
        'default_from' => 'getDefaultFrom',
        'default_to' => 'getDefaultTo',
        'use_same_restrictions_on_all_week' => 'getUseSameRestrictionsOnAllWeek',
        'restrictions' => 'getRestrictions',
        'delivery_zones' => 'getDeliveryZones',
        'reject_on_geocoding_error' => 'getRejectOnGeocodingError',
        'add_delivery_service_cost' => 'getAddDeliveryServiceCost',
        'use_same_delivery_service_product' => 'getUseSameDeliveryServiceProduct',
        'default_delivery_service_product_id' => 'getDefaultDeliveryServiceProductId',
        'use_external_assignation_service' => 'getUseExternalAssignationService',
        'front_trusts_call_center_check' => 'getFrontTrustsCallCenterCheck',
        'external_assignation_service_url' => 'getExternalAssignationServiceUrl',
        'require_exact_address_for_geocoding' => 'getRequireExactAddressForGeocoding',
        'zones_mode' => 'getZonesMode',
        'auto_assign_external_deliveries' => 'getAutoAssignExternalDeliveries',
        'action_on_validation_rejection' => 'getActionOnValidationRejection'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('delivery_geocode_service_type', $data ?? [], null);
        $this->setIfExists('delivery_regions_map_url', $data ?? [], null);
        $this->setIfExists('default_delivery_duration_in_minutes', $data ?? [], null);
        $this->setIfExists('default_self_service_duration_in_minutes', $data ?? [], null);
        $this->setIfExists('use_same_delivery_duration', $data ?? [], null);
        $this->setIfExists('use_same_min_sum', $data ?? [], null);
        $this->setIfExists('default_min_sum', $data ?? [], null);
        $this->setIfExists('use_same_work_time_interval', $data ?? [], null);
        $this->setIfExists('default_from', $data ?? [], null);
        $this->setIfExists('default_to', $data ?? [], null);
        $this->setIfExists('use_same_restrictions_on_all_week', $data ?? [], null);
        $this->setIfExists('restrictions', $data ?? [], null);
        $this->setIfExists('delivery_zones', $data ?? [], null);
        $this->setIfExists('reject_on_geocoding_error', $data ?? [], null);
        $this->setIfExists('add_delivery_service_cost', $data ?? [], null);
        $this->setIfExists('use_same_delivery_service_product', $data ?? [], null);
        $this->setIfExists('default_delivery_service_product_id', $data ?? [], null);
        $this->setIfExists('use_external_assignation_service', $data ?? [], null);
        $this->setIfExists('front_trusts_call_center_check', $data ?? [], null);
        $this->setIfExists('external_assignation_service_url', $data ?? [], null);
        $this->setIfExists('require_exact_address_for_geocoding', $data ?? [], null);
        $this->setIfExists('zones_mode', $data ?? [], null);
        $this->setIfExists('auto_assign_external_deliveries', $data ?? [], null);
        $this->setIfExists('action_on_validation_rejection', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['organization_id'] === null) {
            $invalidProperties[] = "'organization_id' can't be null";
        }
        if ($this->container['delivery_geocode_service_type'] === null) {
            $invalidProperties[] = "'delivery_geocode_service_type' can't be null";
        }
        if ($this->container['delivery_regions_map_url'] === null && !$this->isNullableSetToNull('delivery_regions_map_url')) {
            $invalidProperties[] = "'delivery_regions_map_url' is required";
        }
        if ($this->container['default_delivery_duration_in_minutes'] === null) {
            $invalidProperties[] = "'default_delivery_duration_in_minutes' can't be null";
        }
        if ($this->container['default_self_service_duration_in_minutes'] === null) {
            $invalidProperties[] = "'default_self_service_duration_in_minutes' can't be null";
        }
        if ($this->container['use_same_delivery_duration'] === null) {
            $invalidProperties[] = "'use_same_delivery_duration' can't be null";
        }
        if ($this->container['use_same_min_sum'] === null) {
            $invalidProperties[] = "'use_same_min_sum' can't be null";
        }
        if ($this->container['default_min_sum'] === null && !$this->isNullableSetToNull('default_min_sum')) {
            $invalidProperties[] = "'default_min_sum' is required";
        }
        if ($this->container['use_same_work_time_interval'] === null) {
            $invalidProperties[] = "'use_same_work_time_interval' can't be null";
        }
        if ($this->container['default_from'] === null && !$this->isNullableSetToNull('default_from')) {
            $invalidProperties[] = "'default_from' is required";
        }
        if ($this->container['default_to'] === null && !$this->isNullableSetToNull('default_to')) {
            $invalidProperties[] = "'default_to' is required";
        }
        if ($this->container['use_same_restrictions_on_all_week'] === null) {
            $invalidProperties[] = "'use_same_restrictions_on_all_week' can't be null";
        }
        if ($this->container['restrictions'] === null) {
            $invalidProperties[] = "'restrictions' can't be null";
        }
        if ($this->container['delivery_zones'] === null) {
            $invalidProperties[] = "'delivery_zones' can't be null";
        }
        if ($this->container['reject_on_geocoding_error'] === null) {
            $invalidProperties[] = "'reject_on_geocoding_error' can't be null";
        }
        if ($this->container['add_delivery_service_cost'] === null) {
            $invalidProperties[] = "'add_delivery_service_cost' can't be null";
        }
        if ($this->container['use_same_delivery_service_product'] === null) {
            $invalidProperties[] = "'use_same_delivery_service_product' can't be null";
        }
        if ($this->container['default_delivery_service_product_id'] === null && !$this->isNullableSetToNull('default_delivery_service_product_id')) {
            $invalidProperties[] = "'default_delivery_service_product_id' is required";
        }
        if ($this->container['use_external_assignation_service'] === null) {
            $invalidProperties[] = "'use_external_assignation_service' can't be null";
        }
        if ($this->container['front_trusts_call_center_check'] === null) {
            $invalidProperties[] = "'front_trusts_call_center_check' can't be null";
        }
        if ($this->container['external_assignation_service_url'] === null && !$this->isNullableSetToNull('external_assignation_service_url')) {
            $invalidProperties[] = "'external_assignation_service_url' is required";
        }
        if ($this->container['require_exact_address_for_geocoding'] === null) {
            $invalidProperties[] = "'require_exact_address_for_geocoding' can't be null";
        }
        if ($this->container['zones_mode'] === null) {
            $invalidProperties[] = "'zones_mode' can't be null";
        }
        if ($this->container['auto_assign_external_deliveries'] === null) {
            $invalidProperties[] = "'auto_assign_external_deliveries' can't be null";
        }
        if ($this->container['action_on_validation_rejection'] === null) {
            $invalidProperties[] = "'action_on_validation_rejection' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets organization_id
     *
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string $organization_id Organization ID.                Can be obtained by `/api/1/organizations` operation.
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            throw new \InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets delivery_geocode_service_type
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryGeocodeServiceType
     */
    public function getDeliveryGeocodeServiceType()
    {
        return $this->container['delivery_geocode_service_type'];
    }

    /**
     * Sets delivery_geocode_service_type
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryGeocodeServiceType $delivery_geocode_service_type Geocoding service type.
     *
     * @return self
     */
    public function setDeliveryGeocodeServiceType($delivery_geocode_service_type)
    {
        if (is_null($delivery_geocode_service_type)) {
            throw new \InvalidArgumentException('non-nullable delivery_geocode_service_type cannot be null');
        }
        $this->container['delivery_geocode_service_type'] = $delivery_geocode_service_type;

        return $this;
    }

    /**
     * Gets delivery_regions_map_url
     *
     * @return string|null
     */
    public function getDeliveryRegionsMapUrl()
    {
        return $this->container['delivery_regions_map_url'];
    }

    /**
     * Sets delivery_regions_map_url
     *
     * @param string|null $delivery_regions_map_url Link to the map of delivery service regions.
     *
     * @return self
     */
    public function setDeliveryRegionsMapUrl($delivery_regions_map_url)
    {
        if (is_null($delivery_regions_map_url)) {
            array_push($this->openAPINullablesSetToNull, 'delivery_regions_map_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delivery_regions_map_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delivery_regions_map_url'] = $delivery_regions_map_url;

        return $this;
    }

    /**
     * Gets default_delivery_duration_in_minutes
     *
     * @return int
     */
    public function getDefaultDeliveryDurationInMinutes()
    {
        return $this->container['default_delivery_duration_in_minutes'];
    }

    /**
     * Sets default_delivery_duration_in_minutes
     *
     * @param int $default_delivery_duration_in_minutes General standard of delivery time.
     *
     * @return self
     */
    public function setDefaultDeliveryDurationInMinutes($default_delivery_duration_in_minutes)
    {
        if (is_null($default_delivery_duration_in_minutes)) {
            throw new \InvalidArgumentException('non-nullable default_delivery_duration_in_minutes cannot be null');
        }
        $this->container['default_delivery_duration_in_minutes'] = $default_delivery_duration_in_minutes;

        return $this;
    }

    /**
     * Gets default_self_service_duration_in_minutes
     *
     * @return int
     */
    public function getDefaultSelfServiceDurationInMinutes()
    {
        return $this->container['default_self_service_duration_in_minutes'];
    }

    /**
     * Sets default_self_service_duration_in_minutes
     *
     * @param int $default_self_service_duration_in_minutes Default pickup time.
     *
     * @return self
     */
    public function setDefaultSelfServiceDurationInMinutes($default_self_service_duration_in_minutes)
    {
        if (is_null($default_self_service_duration_in_minutes)) {
            throw new \InvalidArgumentException('non-nullable default_self_service_duration_in_minutes cannot be null');
        }
        $this->container['default_self_service_duration_in_minutes'] = $default_self_service_duration_in_minutes;

        return $this;
    }

    /**
     * Gets use_same_delivery_duration
     *
     * @return bool
     */
    public function getUseSameDeliveryDuration()
    {
        return $this->container['use_same_delivery_duration'];
    }

    /**
     * Sets use_same_delivery_duration
     *
     * @param bool $use_same_delivery_duration Indication that all delivery points in all delivery zones use common delivery time limits.
     *
     * @return self
     */
    public function setUseSameDeliveryDuration($use_same_delivery_duration)
    {
        if (is_null($use_same_delivery_duration)) {
            throw new \InvalidArgumentException('non-nullable use_same_delivery_duration cannot be null');
        }
        $this->container['use_same_delivery_duration'] = $use_same_delivery_duration;

        return $this;
    }

    /**
     * Gets use_same_min_sum
     *
     * @return bool
     */
    public function getUseSameMinSum()
    {
        return $this->container['use_same_min_sum'];
    }

    /**
     * Sets use_same_min_sum
     *
     * @param bool $use_same_min_sum Indication that all delivery points for all delivery zones use the total minimum order amount.
     *
     * @return self
     */
    public function setUseSameMinSum($use_same_min_sum)
    {
        if (is_null($use_same_min_sum)) {
            throw new \InvalidArgumentException('non-nullable use_same_min_sum cannot be null');
        }
        $this->container['use_same_min_sum'] = $use_same_min_sum;

        return $this;
    }

    /**
     * Gets default_min_sum
     *
     * @return float|null
     */
    public function getDefaultMinSum()
    {
        return $this->container['default_min_sum'];
    }

    /**
     * Sets default_min_sum
     *
     * @param float|null $default_min_sum Total minimum order amount.
     *
     * @return self
     */
    public function setDefaultMinSum($default_min_sum)
    {
        if (is_null($default_min_sum)) {
            array_push($this->openAPINullablesSetToNull, 'default_min_sum');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_min_sum', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_min_sum'] = $default_min_sum;

        return $this;
    }

    /**
     * Gets use_same_work_time_interval
     *
     * @return bool
     */
    public function getUseSameWorkTimeInterval()
    {
        return $this->container['use_same_work_time_interval'];
    }

    /**
     * Sets use_same_work_time_interval
     *
     * @param bool $use_same_work_time_interval Indication that all delivery points in all zones use common time limits.
     *
     * @return self
     */
    public function setUseSameWorkTimeInterval($use_same_work_time_interval)
    {
        if (is_null($use_same_work_time_interval)) {
            throw new \InvalidArgumentException('non-nullable use_same_work_time_interval cannot be null');
        }
        $this->container['use_same_work_time_interval'] = $use_same_work_time_interval;

        return $this;
    }

    /**
     * Gets default_from
     *
     * @return int|null
     */
    public function getDefaultFrom()
    {
        return $this->container['default_from'];
    }

    /**
     * Sets default_from
     *
     * @param int|null $default_from The beginning of the interval of the total work time for all points and delivery zones,   in minutes from the beginning of the day.
     *
     * @return self
     */
    public function setDefaultFrom($default_from)
    {
        if (is_null($default_from)) {
            array_push($this->openAPINullablesSetToNull, 'default_from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_from'] = $default_from;

        return $this;
    }

    /**
     * Gets default_to
     *
     * @return int|null
     */
    public function getDefaultTo()
    {
        return $this->container['default_to'];
    }

    /**
     * Sets default_to
     *
     * @param int|null $default_to End of the total work time interval for all points and delivery zones,   in minutes from the beginning of the day.
     *
     * @return self
     */
    public function setDefaultTo($default_to)
    {
        if (is_null($default_to)) {
            array_push($this->openAPINullablesSetToNull, 'default_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_to'] = $default_to;

        return $this;
    }

    /**
     * Gets use_same_restrictions_on_all_week
     *
     * @return bool
     */
    public function getUseSameRestrictionsOnAllWeek()
    {
        return $this->container['use_same_restrictions_on_all_week'];
    }

    /**
     * Sets use_same_restrictions_on_all_week
     *
     * @param bool $use_same_restrictions_on_all_week Indication that all delivery points in all zones use the same schedule for all days of the week.
     *
     * @return self
     */
    public function setUseSameRestrictionsOnAllWeek($use_same_restrictions_on_all_week)
    {
        if (is_null($use_same_restrictions_on_all_week)) {
            throw new \InvalidArgumentException('non-nullable use_same_restrictions_on_all_week cannot be null');
        }
        $this->container['use_same_restrictions_on_all_week'] = $use_same_restrictions_on_all_week;

        return $this;
    }

    /**
     * Gets restrictions
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryRestrictionItem[]
     */
    public function getRestrictions()
    {
        return $this->container['restrictions'];
    }

    /**
     * Sets restrictions
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryRestrictionItem[] $restrictions Restrictions.
     *
     * @return self
     */
    public function setRestrictions($restrictions)
    {
        if (is_null($restrictions)) {
            throw new \InvalidArgumentException('non-nullable restrictions cannot be null');
        }
        $this->container['restrictions'] = $restrictions;

        return $this;
    }

    /**
     * Gets delivery_zones
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryZone[]
     */
    public function getDeliveryZones()
    {
        return $this->container['delivery_zones'];
    }

    /**
     * Sets delivery_zones
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsDeliveryZone[] $delivery_zones Delivery zones.
     *
     * @return self
     */
    public function setDeliveryZones($delivery_zones)
    {
        if (is_null($delivery_zones)) {
            throw new \InvalidArgumentException('non-nullable delivery_zones cannot be null');
        }
        $this->container['delivery_zones'] = $delivery_zones;

        return $this;
    }

    /**
     * Gets reject_on_geocoding_error
     *
     * @return bool
     */
    public function getRejectOnGeocodingError()
    {
        return $this->container['reject_on_geocoding_error'];
    }

    /**
     * Sets reject_on_geocoding_error
     *
     * @param bool $reject_on_geocoding_error Reject delivery if we could not geocode the address.
     *
     * @return self
     */
    public function setRejectOnGeocodingError($reject_on_geocoding_error)
    {
        if (is_null($reject_on_geocoding_error)) {
            throw new \InvalidArgumentException('non-nullable reject_on_geocoding_error cannot be null');
        }
        $this->container['reject_on_geocoding_error'] = $reject_on_geocoding_error;

        return $this;
    }

    /**
     * Gets add_delivery_service_cost
     *
     * @return bool
     */
    public function getAddDeliveryServiceCost()
    {
        return $this->container['add_delivery_service_cost'];
    }

    /**
     * Sets add_delivery_service_cost
     *
     * @param bool $add_delivery_service_cost Add shipping cost to order.
     *
     * @return self
     */
    public function setAddDeliveryServiceCost($add_delivery_service_cost)
    {
        if (is_null($add_delivery_service_cost)) {
            throw new \InvalidArgumentException('non-nullable add_delivery_service_cost cannot be null');
        }
        $this->container['add_delivery_service_cost'] = $add_delivery_service_cost;

        return $this;
    }

    /**
     * Gets use_same_delivery_service_product
     *
     * @return bool
     */
    public function getUseSameDeliveryServiceProduct()
    {
        return $this->container['use_same_delivery_service_product'];
    }

    /**
     * Sets use_same_delivery_service_product
     *
     * @param bool $use_same_delivery_service_product Indication that the cost is the same for all points of delivery.
     *
     * @return self
     */
    public function setUseSameDeliveryServiceProduct($use_same_delivery_service_product)
    {
        if (is_null($use_same_delivery_service_product)) {
            throw new \InvalidArgumentException('non-nullable use_same_delivery_service_product cannot be null');
        }
        $this->container['use_same_delivery_service_product'] = $use_same_delivery_service_product;

        return $this;
    }

    /**
     * Gets default_delivery_service_product_id
     *
     * @return string|null
     */
    public function getDefaultDeliveryServiceProductId()
    {
        return $this->container['default_delivery_service_product_id'];
    }

    /**
     * Sets default_delivery_service_product_id
     *
     * @param string|null $default_delivery_service_product_id Link to \"delivery service payment\".
     *
     * @return self
     */
    public function setDefaultDeliveryServiceProductId($default_delivery_service_product_id)
    {
        if (is_null($default_delivery_service_product_id)) {
            array_push($this->openAPINullablesSetToNull, 'default_delivery_service_product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_delivery_service_product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_delivery_service_product_id'] = $default_delivery_service_product_id;

        return $this;
    }

    /**
     * Gets use_external_assignation_service
     *
     * @return bool
     */
    public function getUseExternalAssignationService()
    {
        return $this->container['use_external_assignation_service'];
    }

    /**
     * Sets use_external_assignation_service
     *
     * @param bool $use_external_assignation_service Use external delivery distribution service.
     *
     * @return self
     */
    public function setUseExternalAssignationService($use_external_assignation_service)
    {
        if (is_null($use_external_assignation_service)) {
            throw new \InvalidArgumentException('non-nullable use_external_assignation_service cannot be null');
        }
        $this->container['use_external_assignation_service'] = $use_external_assignation_service;

        return $this;
    }

    /**
     * Gets front_trusts_call_center_check
     *
     * @return bool
     */
    public function getFrontTrustsCallCenterCheck()
    {
        return $this->container['front_trusts_call_center_check'];
    }

    /**
     * Sets front_trusts_call_center_check
     *
     * @param bool $front_trusts_call_center_check Indication whether or not to trust on the fronts the call center mapping restrictions from the call center  if the composition of the order has not changed since the last check. If true, then trust.
     *
     * @return self
     */
    public function setFrontTrustsCallCenterCheck($front_trusts_call_center_check)
    {
        if (is_null($front_trusts_call_center_check)) {
            throw new \InvalidArgumentException('non-nullable front_trusts_call_center_check cannot be null');
        }
        $this->container['front_trusts_call_center_check'] = $front_trusts_call_center_check;

        return $this;
    }

    /**
     * Gets external_assignation_service_url
     *
     * @return string|null
     */
    public function getExternalAssignationServiceUrl()
    {
        return $this->container['external_assignation_service_url'];
    }

    /**
     * Sets external_assignation_service_url
     *
     * @param string|null $external_assignation_service_url Address of external delivery distribution service.
     *
     * @return self
     */
    public function setExternalAssignationServiceUrl($external_assignation_service_url)
    {
        if (is_null($external_assignation_service_url)) {
            array_push($this->openAPINullablesSetToNull, 'external_assignation_service_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_assignation_service_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_assignation_service_url'] = $external_assignation_service_url;

        return $this;
    }

    /**
     * Gets require_exact_address_for_geocoding
     *
     * @return bool
     */
    public function getRequireExactAddressForGeocoding()
    {
        return $this->container['require_exact_address_for_geocoding'];
    }

    /**
     * Sets require_exact_address_for_geocoding
     *
     * @param bool $require_exact_address_for_geocoding Require an exact geocoding address.
     *
     * @return self
     */
    public function setRequireExactAddressForGeocoding($require_exact_address_for_geocoding)
    {
        if (is_null($require_exact_address_for_geocoding)) {
            throw new \InvalidArgumentException('non-nullable require_exact_address_for_geocoding cannot be null');
        }
        $this->container['require_exact_address_for_geocoding'] = $require_exact_address_for_geocoding;

        return $this;
    }

    /**
     * Gets zones_mode
     *
     * @return \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex
     */
    public function getZonesMode()
    {
        return $this->container['zones_mode'];
    }

    /**
     * Sets zones_mode
     *
     * @param \IIKO\Model\IikoNetServiceContractsApiIikoTransportCustomerIikoNetUserSex $zones_mode Delivery restrictions mode.
     *
     * @return self
     */
    public function setZonesMode($zones_mode)
    {
        if (is_null($zones_mode)) {
            throw new \InvalidArgumentException('non-nullable zones_mode cannot be null');
        }
        $this->container['zones_mode'] = $zones_mode;

        return $this;
    }

    /**
     * Gets auto_assign_external_deliveries
     *
     * @return bool
     */
    public function getAutoAssignExternalDeliveries()
    {
        return $this->container['auto_assign_external_deliveries'];
    }

    /**
     * Sets auto_assign_external_deliveries
     *
     * @param bool $auto_assign_external_deliveries Automatically assigned delivery method based on cartography.
     *
     * @return self
     */
    public function setAutoAssignExternalDeliveries($auto_assign_external_deliveries)
    {
        if (is_null($auto_assign_external_deliveries)) {
            throw new \InvalidArgumentException('non-nullable auto_assign_external_deliveries cannot be null');
        }
        $this->container['auto_assign_external_deliveries'] = $auto_assign_external_deliveries;

        return $this;
    }

    /**
     * Gets action_on_validation_rejection
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsActionOnValidationRejection
     */
    public function getActionOnValidationRejection()
    {
        return $this->container['action_on_validation_rejection'];
    }

    /**
     * Sets action_on_validation_rejection
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveryRestrictionsActionOnValidationRejection $action_on_validation_rejection Action on problems with auto-assignment.
     *
     * @return self
     */
    public function setActionOnValidationRejection($action_on_validation_rejection)
    {
        if (is_null($action_on_validation_rejection)) {
            throw new \InvalidArgumentException('non-nullable action_on_validation_rejection cannot be null');
        }
        $this->container['action_on_validation_rejection'] = $action_on_validation_rejection;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


