<?php
/**
 * IikoTransportPublicApiContractsDeliveriesRequestOrdersByDeliveryDateAndStatusRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * IikoTransportPublicApiContractsDeliveriesRequestOrdersByDeliveryDateAndStatusRequest Class Doc Comment
 *
 * @category Class
 * @description Request for information about orders.
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IikoTransportPublicApiContractsDeliveriesRequestOrdersByDeliveryDateAndStatusRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'iikoTransport.PublicApi.Contracts.Deliveries.Request.OrdersByDeliveryDateAndStatusRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'organization_ids' => 'string[]',
        'delivery_date_from' => 'string',
        'delivery_date_to' => 'string',
        'statuses' => '\IIKO\Model\IikoTransportPublicApiContractsDeliveriesCommonDeliveryStatus[]',
        'source_keys' => 'string[]',
        'courier_ids' => 'string[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'organization_ids' => 'uuid',
        'delivery_date_from' => 'yyyy-MM-dd HH:mm:ss.fff',
        'delivery_date_to' => 'yyyy-MM-dd HH:mm:ss.fff',
        'statuses' => null,
        'source_keys' => null,
        'courier_ids' => 'uuid'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'organization_ids' => false,
        'delivery_date_from' => false,
        'delivery_date_to' => true,
        'statuses' => true,
        'source_keys' => true,
        'courier_ids' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'organization_ids' => 'organizationIds',
        'delivery_date_from' => 'deliveryDateFrom',
        'delivery_date_to' => 'deliveryDateTo',
        'statuses' => 'statuses',
        'source_keys' => 'sourceKeys',
        'courier_ids' => 'courierIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'organization_ids' => 'setOrganizationIds',
        'delivery_date_from' => 'setDeliveryDateFrom',
        'delivery_date_to' => 'setDeliveryDateTo',
        'statuses' => 'setStatuses',
        'source_keys' => 'setSourceKeys',
        'courier_ids' => 'setCourierIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'organization_ids' => 'getOrganizationIds',
        'delivery_date_from' => 'getDeliveryDateFrom',
        'delivery_date_to' => 'getDeliveryDateTo',
        'statuses' => 'getStatuses',
        'source_keys' => 'getSourceKeys',
        'courier_ids' => 'getCourierIds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('organization_ids', $data ?? [], null);
        $this->setIfExists('delivery_date_from', $data ?? [], null);
        $this->setIfExists('delivery_date_to', $data ?? [], null);
        $this->setIfExists('statuses', $data ?? [], null);
        $this->setIfExists('source_keys', $data ?? [], null);
        $this->setIfExists('courier_ids', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['organization_ids'] === null) {
            $invalidProperties[] = "'organization_ids' can't be null";
        }
        if ($this->container['delivery_date_from'] === null) {
            $invalidProperties[] = "'delivery_date_from' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets organization_ids
     *
     * @return string[]
     */
    public function getOrganizationIds()
    {
        return $this->container['organization_ids'];
    }

    /**
     * Sets organization_ids
     *
     * @param string[] $organization_ids Organization ID for which an order search will be performed.                Can be obtained by `/api/1/organizations` operation.
     *
     * @return self
     */
    public function setOrganizationIds($organization_ids)
    {
        if (is_null($organization_ids)) {
            throw new \InvalidArgumentException('non-nullable organization_ids cannot be null');
        }
        $this->container['organization_ids'] = $organization_ids;

        return $this;
    }

    /**
     * Gets delivery_date_from
     *
     * @return string
     */
    public function getDeliveryDateFrom()
    {
        return $this->container['delivery_date_from'];
    }

    /**
     * Sets delivery_date_from
     *
     * @param string $delivery_date_from Order delivery date (Local for delivery terminal). Lower limit.                The guaranteed order availability period is the last 7 days. To access earlier orders, use the `/api/1/deliveries/history/by_delivery_date_and_phone` method.
     *
     * @return self
     */
    public function setDeliveryDateFrom($delivery_date_from)
    {
        if (is_null($delivery_date_from)) {
            throw new \InvalidArgumentException('non-nullable delivery_date_from cannot be null');
        }
        $this->container['delivery_date_from'] = $delivery_date_from;

        return $this;
    }

    /**
     * Gets delivery_date_to
     *
     * @return string|null
     */
    public function getDeliveryDateTo()
    {
        return $this->container['delivery_date_to'];
    }

    /**
     * Sets delivery_date_to
     *
     * @param string|null $delivery_date_to Order delivery date (Local for delivery terminal). Upper limit.
     *
     * @return self
     */
    public function setDeliveryDateTo($delivery_date_to)
    {
        if (is_null($delivery_date_to)) {
            array_push($this->openAPINullablesSetToNull, 'delivery_date_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delivery_date_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delivery_date_to'] = $delivery_date_to;

        return $this;
    }

    /**
     * Gets statuses
     *
     * @return \IIKO\Model\IikoTransportPublicApiContractsDeliveriesCommonDeliveryStatus[]|null
     */
    public function getStatuses()
    {
        return $this->container['statuses'];
    }

    /**
     * Sets statuses
     *
     * @param \IIKO\Model\IikoTransportPublicApiContractsDeliveriesCommonDeliveryStatus[]|null $statuses Allowed order statuses.
     *
     * @return self
     */
    public function setStatuses($statuses)
    {
        if (is_null($statuses)) {
            array_push($this->openAPINullablesSetToNull, 'statuses');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('statuses', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['statuses'] = $statuses;

        return $this;
    }

    /**
     * Gets source_keys
     *
     * @return string[]|null
     */
    public function getSourceKeys()
    {
        return $this->container['source_keys'];
    }

    /**
     * Sets source_keys
     *
     * @param string[]|null $source_keys Source keys.
     *
     * @return self
     */
    public function setSourceKeys($source_keys)
    {
        if (is_null($source_keys)) {
            array_push($this->openAPINullablesSetToNull, 'source_keys');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source_keys', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['source_keys'] = $source_keys;

        return $this;
    }

    /**
     * Gets courier_ids
     *
     * @return string[]|null
     */
    public function getCourierIds()
    {
        return $this->container['courier_ids'];
    }

    /**
     * Sets courier_ids
     *
     * @param string[]|null $courier_ids List of driver IDs.
     *
     * @return self
     */
    public function setCourierIds($courier_ids)
    {
        if (is_null($courier_ids)) {
            array_push($this->openAPINullablesSetToNull, 'courier_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('courier_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['courier_ids'] = $courier_ids;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


