<?php
/**
 * IncomingServiceUpdateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iikoCloud API
 *
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IIKO\Model;

use \ArrayAccess;
use \IIKO\ObjectSerializer;

/**
 * IncomingServiceUpdateRequest Class Doc Comment
 *
 * @category Class
 * @package  IIKO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IncomingServiceUpdateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'IncomingServiceUpdateRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'comment' => 'string',
        'conception' => 'string',
        'contract_date' => 'string',
        'contract_number' => 'string',
        'counteragent' => 'string',
        'date' => 'string',
        'document_id' => 'string',
        'due_date' => 'string',
        'employee_pass_to_account' => 'string',
        'incoming_date' => 'string',
        'incoming_document_number' => 'string',
        'invoice' => 'string',
        'is_automatic' => 'bool',
        'is_editable' => 'bool',
        'items' => '\IIKO\Model\IncomingServiceCreateItem[]',
        'number' => 'string',
        'organization_id' => 'string',
        'revenue_account' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'comment' => null,
        'conception' => null,
        'contract_date' => null,
        'contract_number' => null,
        'counteragent' => null,
        'date' => null,
        'document_id' => null,
        'due_date' => null,
        'employee_pass_to_account' => null,
        'incoming_date' => null,
        'incoming_document_number' => null,
        'invoice' => null,
        'is_automatic' => null,
        'is_editable' => null,
        'items' => null,
        'number' => null,
        'organization_id' => null,
        'revenue_account' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'comment' => false,
        'conception' => false,
        'contract_date' => false,
        'contract_number' => false,
        'counteragent' => false,
        'date' => false,
        'document_id' => false,
        'due_date' => false,
        'employee_pass_to_account' => false,
        'incoming_date' => false,
        'incoming_document_number' => false,
        'invoice' => false,
        'is_automatic' => false,
        'is_editable' => false,
        'items' => false,
        'number' => false,
        'organization_id' => false,
        'revenue_account' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'comment' => 'comment',
        'conception' => 'conception',
        'contract_date' => 'contractDate',
        'contract_number' => 'contractNumber',
        'counteragent' => 'counteragent',
        'date' => 'date',
        'document_id' => 'documentId',
        'due_date' => 'dueDate',
        'employee_pass_to_account' => 'employeePassToAccount',
        'incoming_date' => 'incomingDate',
        'incoming_document_number' => 'incomingDocumentNumber',
        'invoice' => 'invoice',
        'is_automatic' => 'isAutomatic',
        'is_editable' => 'isEditable',
        'items' => 'items',
        'number' => 'number',
        'organization_id' => 'organizationId',
        'revenue_account' => 'revenueAccount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'comment' => 'setComment',
        'conception' => 'setConception',
        'contract_date' => 'setContractDate',
        'contract_number' => 'setContractNumber',
        'counteragent' => 'setCounteragent',
        'date' => 'setDate',
        'document_id' => 'setDocumentId',
        'due_date' => 'setDueDate',
        'employee_pass_to_account' => 'setEmployeePassToAccount',
        'incoming_date' => 'setIncomingDate',
        'incoming_document_number' => 'setIncomingDocumentNumber',
        'invoice' => 'setInvoice',
        'is_automatic' => 'setIsAutomatic',
        'is_editable' => 'setIsEditable',
        'items' => 'setItems',
        'number' => 'setNumber',
        'organization_id' => 'setOrganizationId',
        'revenue_account' => 'setRevenueAccount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'comment' => 'getComment',
        'conception' => 'getConception',
        'contract_date' => 'getContractDate',
        'contract_number' => 'getContractNumber',
        'counteragent' => 'getCounteragent',
        'date' => 'getDate',
        'document_id' => 'getDocumentId',
        'due_date' => 'getDueDate',
        'employee_pass_to_account' => 'getEmployeePassToAccount',
        'incoming_date' => 'getIncomingDate',
        'incoming_document_number' => 'getIncomingDocumentNumber',
        'invoice' => 'getInvoice',
        'is_automatic' => 'getIsAutomatic',
        'is_editable' => 'getIsEditable',
        'items' => 'getItems',
        'number' => 'getNumber',
        'organization_id' => 'getOrganizationId',
        'revenue_account' => 'getRevenueAccount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('comment', $data ?? [], null);
        $this->setIfExists('conception', $data ?? [], null);
        $this->setIfExists('contract_date', $data ?? [], null);
        $this->setIfExists('contract_number', $data ?? [], null);
        $this->setIfExists('counteragent', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('document_id', $data ?? [], null);
        $this->setIfExists('due_date', $data ?? [], null);
        $this->setIfExists('employee_pass_to_account', $data ?? [], null);
        $this->setIfExists('incoming_date', $data ?? [], null);
        $this->setIfExists('incoming_document_number', $data ?? [], null);
        $this->setIfExists('invoice', $data ?? [], null);
        $this->setIfExists('is_automatic', $data ?? [], null);
        $this->setIfExists('is_editable', $data ?? [], null);
        $this->setIfExists('items', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('revenue_account', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['counteragent'] === null) {
            $invalidProperties[] = "'counteragent' can't be null";
        }
        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ($this->container['document_id'] === null) {
            $invalidProperties[] = "'document_id' can't be null";
        }
        if ($this->container['items'] === null) {
            $invalidProperties[] = "'items' can't be null";
        }
        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if ($this->container['organization_id'] === null) {
            $invalidProperties[] = "'organization_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment Comment
     *
     * @return self
     */
    public function setComment($comment)
    {
        if (is_null($comment)) {
            throw new \InvalidArgumentException('non-nullable comment cannot be null');
        }
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets conception
     *
     * @return string|null
     */
    public function getConception()
    {
        return $this->container['conception'];
    }

    /**
     * Sets conception
     *
     * @param string|null $conception Concept identifier (GUID)
     *
     * @return self
     */
    public function setConception($conception)
    {
        if (is_null($conception)) {
            throw new \InvalidArgumentException('non-nullable conception cannot be null');
        }
        $this->container['conception'] = $conception;

        return $this;
    }

    /**
     * Gets contract_date
     *
     * @return string|null
     */
    public function getContractDate()
    {
        return $this->container['contract_date'];
    }

    /**
     * Sets contract_date
     *
     * @param string|null $contract_date Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)
     *
     * @return self
     */
    public function setContractDate($contract_date)
    {
        if (is_null($contract_date)) {
            throw new \InvalidArgumentException('non-nullable contract_date cannot be null');
        }
        $this->container['contract_date'] = $contract_date;

        return $this;
    }

    /**
     * Gets contract_number
     *
     * @return string|null
     */
    public function getContractNumber()
    {
        return $this->container['contract_number'];
    }

    /**
     * Sets contract_number
     *
     * @param string|null $contract_number Contract number
     *
     * @return self
     */
    public function setContractNumber($contract_number)
    {
        if (is_null($contract_number)) {
            throw new \InvalidArgumentException('non-nullable contract_number cannot be null');
        }
        $this->container['contract_number'] = $contract_number;

        return $this;
    }

    /**
     * Gets counteragent
     *
     * @return string
     */
    public function getCounteragent()
    {
        return $this->container['counteragent'];
    }

    /**
     * Sets counteragent
     *
     * @param string $counteragent Counteragent identifier (GUID)
     *
     * @return self
     */
    public function setCounteragent($counteragent)
    {
        if (is_null($counteragent)) {
            throw new \InvalidArgumentException('non-nullable counteragent cannot be null');
        }
        $this->container['counteragent'] = $counteragent;

        return $this;
    }

    /**
     * Gets date
     *
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string $date Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets document_id
     *
     * @return string
     */
    public function getDocumentId()
    {
        return $this->container['document_id'];
    }

    /**
     * Sets document_id
     *
     * @param string $document_id Document identifier (GUID)
     *
     * @return self
     */
    public function setDocumentId($document_id)
    {
        if (is_null($document_id)) {
            throw new \InvalidArgumentException('non-nullable document_id cannot be null');
        }
        $this->container['document_id'] = $document_id;

        return $this;
    }

    /**
     * Gets due_date
     *
     * @return string|null
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     *
     * @param string|null $due_date Payment due date
     *
     * @return self
     */
    public function setDueDate($due_date)
    {
        if (is_null($due_date)) {
            throw new \InvalidArgumentException('non-nullable due_date cannot be null');
        }
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets employee_pass_to_account
     *
     * @return string|null
     */
    public function getEmployeePassToAccount()
    {
        return $this->container['employee_pass_to_account'];
    }

    /**
     * Sets employee_pass_to_account
     *
     * @param string|null $employee_pass_to_account Charge to employee
     *
     * @return self
     */
    public function setEmployeePassToAccount($employee_pass_to_account)
    {
        if (is_null($employee_pass_to_account)) {
            throw new \InvalidArgumentException('non-nullable employee_pass_to_account cannot be null');
        }
        $this->container['employee_pass_to_account'] = $employee_pass_to_account;

        return $this;
    }

    /**
     * Gets incoming_date
     *
     * @return string|null
     */
    public function getIncomingDate()
    {
        return $this->container['incoming_date'];
    }

    /**
     * Sets incoming_date
     *
     * @param string|null $incoming_date Incoming document date (YYYY-MM-DD)
     *
     * @return self
     */
    public function setIncomingDate($incoming_date)
    {
        if (is_null($incoming_date)) {
            throw new \InvalidArgumentException('non-nullable incoming_date cannot be null');
        }
        $this->container['incoming_date'] = $incoming_date;

        return $this;
    }

    /**
     * Gets incoming_document_number
     *
     * @return string|null
     */
    public function getIncomingDocumentNumber()
    {
        return $this->container['incoming_document_number'];
    }

    /**
     * Sets incoming_document_number
     *
     * @param string|null $incoming_document_number Incoming external document number
     *
     * @return self
     */
    public function setIncomingDocumentNumber($incoming_document_number)
    {
        if (is_null($incoming_document_number)) {
            throw new \InvalidArgumentException('non-nullable incoming_document_number cannot be null');
        }
        $this->container['incoming_document_number'] = $incoming_document_number;

        return $this;
    }

    /**
     * Gets invoice
     *
     * @return string|null
     */
    public function getInvoice()
    {
        return $this->container['invoice'];
    }

    /**
     * Sets invoice
     *
     * @param string|null $invoice Invoice number
     *
     * @return self
     */
    public function setInvoice($invoice)
    {
        if (is_null($invoice)) {
            throw new \InvalidArgumentException('non-nullable invoice cannot be null');
        }
        $this->container['invoice'] = $invoice;

        return $this;
    }

    /**
     * Gets is_automatic
     *
     * @return bool|null
     */
    public function getIsAutomatic()
    {
        return $this->container['is_automatic'];
    }

    /**
     * Sets is_automatic
     *
     * @param bool|null $is_automatic Automatic document creation flag
     *
     * @return self
     */
    public function setIsAutomatic($is_automatic)
    {
        if (is_null($is_automatic)) {
            throw new \InvalidArgumentException('non-nullable is_automatic cannot be null');
        }
        $this->container['is_automatic'] = $is_automatic;

        return $this;
    }

    /**
     * Gets is_editable
     *
     * @return bool|null
     */
    public function getIsEditable()
    {
        return $this->container['is_editable'];
    }

    /**
     * Sets is_editable
     *
     * @param bool|null $is_editable Editable flag. true — available for editing in RMS
     *
     * @return self
     */
    public function setIsEditable($is_editable)
    {
        if (is_null($is_editable)) {
            throw new \InvalidArgumentException('non-nullable is_editable cannot be null');
        }
        $this->container['is_editable'] = $is_editable;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \IIKO\Model\IncomingServiceCreateItem[]
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \IIKO\Model\IncomingServiceCreateItem[] $items List of document items
     *
     * @return self
     */
    public function setItems($items)
    {
        if (is_null($items)) {
            throw new \InvalidArgumentException('non-nullable items cannot be null');
        }
        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string $number Document number
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            throw new \InvalidArgumentException('non-nullable number cannot be null');
        }
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string $organization_id Organization identifier (GUID)
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            throw new \InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets revenue_account
     *
     * @return string|null
     */
    public function getRevenueAccount()
    {
        return $this->container['revenue_account'];
    }

    /**
     * Sets revenue_account
     *
     * @param string|null $revenue_account Revenue account identifier (GUID)
     *
     * @return self
     */
    public function setRevenueAccount($revenue_account)
    {
        if (is_null($revenue_account)) {
            throw new \InvalidArgumentException('non-nullable revenue_account cannot be null');
        }
        $this->container['revenue_account'] = $revenue_account;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


