all:
  children:
    controlplane:
      hosts:
        control-plane:
          ansible_host: 127.0.0.1
          ansible_connection: local
    dataplane:
      children:
        canary:
          hosts:
            test-owner:
              ansible_host: 127.0.0.1
              ansible_connection: local
        production:
          hosts:
            test-owner:
              ansible_host: 127.0.0.1
              ansible_connection: local
