<?php
/**
 * ReceiptDataItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  YOOMONEY
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YooMoney API Reference
 *
 * The YooMoney API Reference describes all the YooMoney API methods. The API allows you to process online payments via different methods and make payouts. More about integration via the YooMoney API: Integration guide: https://yookassa.ru/developers: description of payment solutions based on the YooMoney API as well as links to detailed instructions.; Interaction format: https://yookassa.ru/developers/using-api/interaction-format: description of request formats, requirements for request authentication and idempotency key, specifics of response processing.; OpenAPI specification: https://yookassa.ru/developers/using-api/openapi-specification: information about the YooMoney API specification, link for downloading the specification in the YAML format.; Ready-made SDK: https://yookassa.ru/developers/using-api/using-sdks: links to ready-made solutions for PHP, Python, and other programming languages.; Incoming notifications: https://yookassa.ru/developers/using-api/webhooks: description of the operating procedure for notifications (webhook, callback) sent to track object statuses. YooMoney API changelog: https://yookassa.ru/developers/using-api/changelog
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YOOMONEY\Model;

use \ArrayAccess;
use \YOOMONEY\ObjectSerializer;

/**
 * ReceiptDataItem Class Doc Comment
 *
 * @category Class
 * @description Информация о товарной позиции в заказе. Используется для формирования чека.
 * @package  YOOMONEY
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReceiptDataItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ReceiptDataItem';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'description' => 'string',
        'amount' => '\YOOMONEY\Model\MonetaryAmount',
        'vat_code' => 'int',
        'quantity' => 'float',
        'measure' => '\YOOMONEY\Model\ReceiptItemMeasure',
        'mark_quantity' => '\YOOMONEY\Model\MarkQuantity',
        'payment_subject' => '\YOOMONEY\Model\ReceiptItemPaymentSubject',
        'payment_mode' => '\YOOMONEY\Model\ReceiptItemPaymentMode',
        'country_of_origin_code' => 'string',
        'customs_declaration_number' => 'string',
        'excise' => 'string',
        'product_code' => 'string',
        'planned_status' => 'int',
        'mark_code_info' => '\YOOMONEY\Model\MarkCodeInfo',
        'mark_mode' => 'string',
        'payment_subject_industry_details' => '\YOOMONEY\Model\IndustryDetails[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'description' => null,
        'amount' => null,
        'vat_code' => 'int32',
        'quantity' => null,
        'measure' => null,
        'mark_quantity' => null,
        'payment_subject' => null,
        'payment_mode' => null,
        'country_of_origin_code' => null,
        'customs_declaration_number' => null,
        'excise' => null,
        'product_code' => null,
        'planned_status' => 'int32',
        'mark_code_info' => null,
        'mark_mode' => null,
        'payment_subject_industry_details' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'description' => false,
        'amount' => false,
        'vat_code' => false,
        'quantity' => false,
        'measure' => false,
        'mark_quantity' => false,
        'payment_subject' => false,
        'payment_mode' => false,
        'country_of_origin_code' => false,
        'customs_declaration_number' => false,
        'excise' => false,
        'product_code' => false,
        'planned_status' => false,
        'mark_code_info' => false,
        'mark_mode' => false,
        'payment_subject_industry_details' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'description' => 'description',
        'amount' => 'amount',
        'vat_code' => 'vat_code',
        'quantity' => 'quantity',
        'measure' => 'measure',
        'mark_quantity' => 'mark_quantity',
        'payment_subject' => 'payment_subject',
        'payment_mode' => 'payment_mode',
        'country_of_origin_code' => 'country_of_origin_code',
        'customs_declaration_number' => 'customs_declaration_number',
        'excise' => 'excise',
        'product_code' => 'product_code',
        'planned_status' => 'planned_status',
        'mark_code_info' => 'mark_code_info',
        'mark_mode' => 'mark_mode',
        'payment_subject_industry_details' => 'payment_subject_industry_details'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'description' => 'setDescription',
        'amount' => 'setAmount',
        'vat_code' => 'setVatCode',
        'quantity' => 'setQuantity',
        'measure' => 'setMeasure',
        'mark_quantity' => 'setMarkQuantity',
        'payment_subject' => 'setPaymentSubject',
        'payment_mode' => 'setPaymentMode',
        'country_of_origin_code' => 'setCountryOfOriginCode',
        'customs_declaration_number' => 'setCustomsDeclarationNumber',
        'excise' => 'setExcise',
        'product_code' => 'setProductCode',
        'planned_status' => 'setPlannedStatus',
        'mark_code_info' => 'setMarkCodeInfo',
        'mark_mode' => 'setMarkMode',
        'payment_subject_industry_details' => 'setPaymentSubjectIndustryDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'description' => 'getDescription',
        'amount' => 'getAmount',
        'vat_code' => 'getVatCode',
        'quantity' => 'getQuantity',
        'measure' => 'getMeasure',
        'mark_quantity' => 'getMarkQuantity',
        'payment_subject' => 'getPaymentSubject',
        'payment_mode' => 'getPaymentMode',
        'country_of_origin_code' => 'getCountryOfOriginCode',
        'customs_declaration_number' => 'getCustomsDeclarationNumber',
        'excise' => 'getExcise',
        'product_code' => 'getProductCode',
        'planned_status' => 'getPlannedStatus',
        'mark_code_info' => 'getMarkCodeInfo',
        'mark_mode' => 'getMarkMode',
        'payment_subject_industry_details' => 'getPaymentSubjectIndustryDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('vat_code', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('measure', $data ?? [], null);
        $this->setIfExists('mark_quantity', $data ?? [], null);
        $this->setIfExists('payment_subject', $data ?? [], null);
        $this->setIfExists('payment_mode', $data ?? [], null);
        $this->setIfExists('country_of_origin_code', $data ?? [], null);
        $this->setIfExists('customs_declaration_number', $data ?? [], null);
        $this->setIfExists('excise', $data ?? [], null);
        $this->setIfExists('product_code', $data ?? [], null);
        $this->setIfExists('planned_status', $data ?? [], null);
        $this->setIfExists('mark_code_info', $data ?? [], null);
        $this->setIfExists('mark_mode', $data ?? [], null);
        $this->setIfExists('payment_subject_industry_details', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['vat_code'] === null) {
            $invalidProperties[] = "'vat_code' can't be null";
        }
        if (($this->container['vat_code'] > 12)) {
            $invalidProperties[] = "invalid value for 'vat_code', must be smaller than or equal to 12.";
        }

        if (($this->container['vat_code'] < 1)) {
            $invalidProperties[] = "invalid value for 'vat_code', must be bigger than or equal to 1.";
        }

        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if (!is_null($this->container['customs_declaration_number']) && (mb_strlen($this->container['customs_declaration_number']) > 32)) {
            $invalidProperties[] = "invalid value for 'customs_declaration_number', the character length must be smaller than or equal to 32.";
        }

        if (!is_null($this->container['customs_declaration_number']) && (mb_strlen($this->container['customs_declaration_number']) < 1)) {
            $invalidProperties[] = "invalid value for 'customs_declaration_number', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['planned_status']) && ($this->container['planned_status'] > 6)) {
            $invalidProperties[] = "invalid value for 'planned_status', must be smaller than or equal to 6.";
        }

        if (!is_null($this->container['planned_status']) && ($this->container['planned_status'] < 1)) {
            $invalidProperties[] = "invalid value for 'planned_status', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['mark_mode']) && !preg_match("/^[0]{1}$/", $this->container['mark_mode'])) {
            $invalidProperties[] = "invalid value for 'mark_mode', must be conform to the pattern /^[0]{1}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Название товара (от 1 до 128 символов). Тег в 54 ФЗ — 1030.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return \YOOMONEY\Model\MonetaryAmount
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param \YOOMONEY\Model\MonetaryAmount $amount Цена товара (тег в 54 ФЗ — 1079).
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets vat_code
     *
     * @return int
     */
    public function getVatCode()
    {
        return $this->container['vat_code'];
    }

    /**
     * Sets vat_code
     *
     * @param int $vat_code Ставка НДС (тег в 54 ФЗ — 1199). Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#vat-codes * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#vat-codes
     *
     * @return self
     */
    public function setVatCode($vat_code)
    {
        if (is_null($vat_code)) {
            throw new \InvalidArgumentException('non-nullable vat_code cannot be null');
        }

        if (($vat_code > 12)) {
            throw new \InvalidArgumentException('invalid value for $vat_code when calling ReceiptDataItem., must be smaller than or equal to 12.');
        }
        if (($vat_code < 1)) {
            throw new \InvalidArgumentException('invalid value for $vat_code when calling ReceiptDataItem., must be bigger than or equal to 1.');
        }

        $this->container['vat_code'] = $vat_code;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float $quantity Product quantity (tag 1023 in 54-FZ). You can set an integer or a decimal value. The decimal separator is a dot; there is no thousands separator. The maximum possible value and the maximum number of digits after the decimal separator (for decimal values) depend on the model of your online sales register. For Receipts from YooMoney, the maximum possible value is 99999.999, with no more than 3 digits after the decimal separator.
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets measure
     *
     * @return \YOOMONEY\Model\ReceiptItemMeasure|null
     */
    public function getMeasure()
    {
        return $this->container['measure'];
    }

    /**
     * Sets measure
     *
     * @param \YOOMONEY\Model\ReceiptItemMeasure|null $measure measure
     *
     * @return self
     */
    public function setMeasure($measure)
    {
        if (is_null($measure)) {
            throw new \InvalidArgumentException('non-nullable measure cannot be null');
        }
        $this->container['measure'] = $measure;

        return $this;
    }

    /**
     * Gets mark_quantity
     *
     * @return \YOOMONEY\Model\MarkQuantity|null
     */
    public function getMarkQuantity()
    {
        return $this->container['mark_quantity'];
    }

    /**
     * Sets mark_quantity
     *
     * @param \YOOMONEY\Model\MarkQuantity|null $mark_quantity mark_quantity
     *
     * @return self
     */
    public function setMarkQuantity($mark_quantity)
    {
        if (is_null($mark_quantity)) {
            throw new \InvalidArgumentException('non-nullable mark_quantity cannot be null');
        }
        $this->container['mark_quantity'] = $mark_quantity;

        return $this;
    }

    /**
     * Gets payment_subject
     *
     * @return \YOOMONEY\Model\ReceiptItemPaymentSubject|null
     */
    public function getPaymentSubject()
    {
        return $this->container['payment_subject'];
    }

    /**
     * Sets payment_subject
     *
     * @param \YOOMONEY\Model\ReceiptItemPaymentSubject|null $payment_subject payment_subject
     *
     * @return self
     */
    public function setPaymentSubject($payment_subject)
    {
        if (is_null($payment_subject)) {
            throw new \InvalidArgumentException('non-nullable payment_subject cannot be null');
        }
        $this->container['payment_subject'] = $payment_subject;

        return $this;
    }

    /**
     * Gets payment_mode
     *
     * @return \YOOMONEY\Model\ReceiptItemPaymentMode|null
     */
    public function getPaymentMode()
    {
        return $this->container['payment_mode'];
    }

    /**
     * Sets payment_mode
     *
     * @param \YOOMONEY\Model\ReceiptItemPaymentMode|null $payment_mode payment_mode
     *
     * @return self
     */
    public function setPaymentMode($payment_mode)
    {
        if (is_null($payment_mode)) {
            throw new \InvalidArgumentException('non-nullable payment_mode cannot be null');
        }
        $this->container['payment_mode'] = $payment_mode;

        return $this;
    }

    /**
     * Gets country_of_origin_code
     *
     * @return string|null
     */
    public function getCountryOfOriginCode()
    {
        return $this->container['country_of_origin_code'];
    }

    /**
     * Sets country_of_origin_code
     *
     * @param string|null $country_of_origin_code Код страны происхождения товара по общероссийскому классификатору стран мира (OК (MК (ИСО 3166) 004-97) 025-2001: http://docs.cntd.ru/document/842501280). Тег в 54 ФЗ — 1230. Пример: RU. Можно передавать, если используете онлайн-кассу Orange Data, Кит Инвест.
     *
     * @return self
     */
    public function setCountryOfOriginCode($country_of_origin_code)
    {
        if (is_null($country_of_origin_code)) {
            throw new \InvalidArgumentException('non-nullable country_of_origin_code cannot be null');
        }
        $this->container['country_of_origin_code'] = $country_of_origin_code;

        return $this;
    }

    /**
     * Gets customs_declaration_number
     *
     * @return string|null
     */
    public function getCustomsDeclarationNumber()
    {
        return $this->container['customs_declaration_number'];
    }

    /**
     * Sets customs_declaration_number
     *
     * @param string|null $customs_declaration_number Номер таможенной декларации (от 1 до 32 символов). Тег в 54 ФЗ — 1231. Можно передавать, если используете онлайн-кассу Orange Data, Кит Инвест.
     *
     * @return self
     */
    public function setCustomsDeclarationNumber($customs_declaration_number)
    {
        if (is_null($customs_declaration_number)) {
            throw new \InvalidArgumentException('non-nullable customs_declaration_number cannot be null');
        }
        if ((mb_strlen($customs_declaration_number) > 32)) {
            throw new \InvalidArgumentException('invalid length for $customs_declaration_number when calling ReceiptDataItem., must be smaller than or equal to 32.');
        }
        if ((mb_strlen($customs_declaration_number) < 1)) {
            throw new \InvalidArgumentException('invalid length for $customs_declaration_number when calling ReceiptDataItem., must be bigger than or equal to 1.');
        }

        $this->container['customs_declaration_number'] = $customs_declaration_number;

        return $this;
    }

    /**
     * Gets excise
     *
     * @return string|null
     */
    public function getExcise()
    {
        return $this->container['excise'];
    }

    /**
     * Sets excise
     *
     * @param string|null $excise Сумма акциза товара с учетом копеек (тег в 54 ФЗ — 1229). Десятичное число с точностью до 2 знаков после точки. Можно передавать, если используете онлайн-кассу Orange Data, Кит Инвест.
     *
     * @return self
     */
    public function setExcise($excise)
    {
        if (is_null($excise)) {
            throw new \InvalidArgumentException('non-nullable excise cannot be null');
        }
        $this->container['excise'] = $excise;

        return $this;
    }

    /**
     * Gets product_code
     *
     * @return string|null
     */
    public function getProductCode()
    {
        return $this->container['product_code'];
    }

    /**
     * Sets product_code
     *
     * @param string|null $product_code Product code (tag 1162 in 54-FZ) is a unique number assigned to a unit of product during marking process. Format: hexadecimal number with spaces. Maximum length is 32 bytes. Example: 00 00 00 01 00 21 FA 41 00 23 05 41 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 12 00 AB 00. This parameter is required if both conditions apply: your online sales register is updated to FFD 1.05 or 1.1; the product is subject to mandatory marking: http://docs.cntd.ru/document/902192509. The parameter must not be included in the request if you are using Receipts from YooMoney: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/basics or an online sales register updated to FFD 1.2: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/marking.
     *
     * @return self
     */
    public function setProductCode($product_code)
    {
        if (is_null($product_code)) {
            throw new \InvalidArgumentException('non-nullable product_code cannot be null');
        }
        $this->container['product_code'] = $product_code;

        return $this;
    }

    /**
     * Gets planned_status
     *
     * @return int|null
     */
    public function getPlannedStatus()
    {
        return $this->container['planned_status'];
    }

    /**
     * Sets planned_status
     *
     * @param int|null $planned_status Planned product status. Tag in 54-FZ: 2003. To be specified only for products that are subject to mandatory marking (parameter gs_1m, short, or fur is set in items.mark_code_info). Possible values are: for Receipts from YooMoney: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#planned-status; for third party online sales registers: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#planned-status.
     *
     * @return self
     */
    public function setPlannedStatus($planned_status)
    {
        if (is_null($planned_status)) {
            throw new \InvalidArgumentException('non-nullable planned_status cannot be null');
        }

        if (($planned_status > 6)) {
            throw new \InvalidArgumentException('invalid value for $planned_status when calling ReceiptDataItem., must be smaller than or equal to 6.');
        }
        if (($planned_status < 1)) {
            throw new \InvalidArgumentException('invalid value for $planned_status when calling ReceiptDataItem., must be bigger than or equal to 1.');
        }

        $this->container['planned_status'] = $planned_status;

        return $this;
    }

    /**
     * Gets mark_code_info
     *
     * @return \YOOMONEY\Model\MarkCodeInfo|null
     */
    public function getMarkCodeInfo()
    {
        return $this->container['mark_code_info'];
    }

    /**
     * Sets mark_code_info
     *
     * @param \YOOMONEY\Model\MarkCodeInfo|null $mark_code_info mark_code_info
     *
     * @return self
     */
    public function setMarkCodeInfo($mark_code_info)
    {
        if (is_null($mark_code_info)) {
            throw new \InvalidArgumentException('non-nullable mark_code_info cannot be null');
        }
        $this->container['mark_code_info'] = $mark_code_info;

        return $this;
    }

    /**
     * Gets mark_mode
     *
     * @return string|null
     */
    public function getMarkMode()
    {
        return $this->container['mark_mode'];
    }

    /**
     * Sets mark_mode
     *
     * @param string|null $mark_mode Режим обработки кода маркировки (тег в 54 ФЗ — 2102). Обязательный параметр, если одновременно выполняются эти условия: * вы используете Чеки от ЮKassa или онлайн-кассу Атол Онлайн или BusinessRu, обновленную до ФФД 1.2; * товар нужно маркировать: http://docs.cntd.ru/document/902192509. Должен принимать значение равное «0».
     *
     * @return self
     */
    public function setMarkMode($mark_mode)
    {
        if (is_null($mark_mode)) {
            throw new \InvalidArgumentException('non-nullable mark_mode cannot be null');
        }

        if ((!preg_match("/^[0]{1}$/", ObjectSerializer::toString($mark_mode)))) {
            throw new \InvalidArgumentException("invalid value for \$mark_mode when calling ReceiptDataItem., must conform to the pattern /^[0]{1}$/.");
        }

        $this->container['mark_mode'] = $mark_mode;

        return $this;
    }

    /**
     * Gets payment_subject_industry_details
     *
     * @return \YOOMONEY\Model\IndustryDetails[]|null
     */
    public function getPaymentSubjectIndustryDetails()
    {
        return $this->container['payment_subject_industry_details'];
    }

    /**
     * Sets payment_subject_industry_details
     *
     * @param \YOOMONEY\Model\IndustryDetails[]|null $payment_subject_industry_details Отраслевой реквизит предмета расчета (тег в 54 ФЗ — 1260). Можно передавать, если используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2.
     *
     * @return self
     */
    public function setPaymentSubjectIndustryDetails($payment_subject_industry_details)
    {
        if (is_null($payment_subject_industry_details)) {
            throw new \InvalidArgumentException('non-nullable payment_subject_industry_details cannot be null');
        }
        $this->container['payment_subject_industry_details'] = $payment_subject_industry_details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


